- manifest.json
`${account}` --> `{{account}}`
> Fix outbound policies to replace account field

- manifest.json
- node/resolvers/httpResolver.ts
Add a domain to the cookie set by the resolver.
The cookie set without a host domain was ignored by the checkout.
> Set correct host domain for cookies

- CHANGELOG.md
- graphql/types/Product.graphql
- manifest.json
- node/resolvers/catalog/fieldsResolver.ts
Add product clusters property (the collections of products) to the product query
> Add product clusters property to the product query

- manifest.json
- node/service.json
> Adding service json

- graphql/types/Product.graphql
- manifest.json
- node/resolvers/catalog/fieldsResolver.ts
Add specifications to product schema.
> Add specifications to product

- graphql/types/Brand.graphql
- graphql/types/Category.graphql
- graphql/types/Product.graphql
- manifest.json
Adds graphql cache to product, brand and categories
> Adding cache to graphql schema

- manifest.json
- node/resolvers/document/index.ts
Fix masterdata resolvers
Fix masterdata resolvers
> Fix masterdata resolvers

- manifest.json
- node/resolvers/paths.ts
> Removing hardcoded strings

- graphql/types/Product.graphql
- manifest.json
- node/graphql/index.ts
- node/resolvers/catalog/index.ts
- node/resolvers/paths.ts
> Add kitItems

- graphql/schema.graphql
- manifest.json
- node/resolvers/document/index.ts
- node/resolvers/headers.ts
Implement pagination on MD results
GraphiQL in vtexhackathon04:
```
query {
documents(acronym: "CC", fields:["_all"], start: 0, pageSize: 20) {
id
}
}
```
> Impement MD pagination

- CHANGELOG.md
- node/resolvers/profile/profileResolver.ts
Fix cookie name to reflect the changes made in authentication resolver.
> Fix profile query to reflect changes that were made in auth resolver.

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Brand.graphql
- graphql/types/Category.graphql
- graphql/types/Product.graphql
> Sets cache hints to schema root fields 

- CHANGELOG.md
- graphql/types/Auth.graphql
- manifest.json
Remove VtexTemporarySession to AuthInput
> Remove VtexTemporarySession to AuthInput

- CHANGELOG.md
- graphql/schema.graphql
- node/resolvers/auth/index.ts
Create logout mutation
Using `Set-cookie` to remove the auth token of the user.
> Create logout mutation

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Auth.graphql
- node/axiosConfig.ts
- node/errors/resolverError.ts
- node/graphql/index.ts
- node/resolvers/catalog/fieldsResolver.ts
- node/resolvers/catalog/index.ts
- node/resolvers/document/index.ts
- node/resolvers/headers.ts
- node/resolvers/httpResolver.ts
- node/resolvers/paths.ts
- node/resolvers/profile/index.ts
- node/resolvers/profile/profileResolver.ts
- node/tsconfig.json
- node/typings/colossus.d.ts
I will add the graphql documentation to make an easy journey to the partners through GraphiQL tool.
**Just look the Auth.graphql file**
https://login--storecomponents.myvtexdev.com/_v/vtex.store-graphql/graphiql/v1
> Add documentation in graphql files and apply eslint

- CHANGELOG.md
- graphql/schema.graphql
Add more docs in schema.graphql
> Add more docs in schema.graphql

- CHANGELOG.md
- node/resolvers/paths.ts
Reorganize `paths.ts` by API's. 
https://login--storecomponents.myvtex.com/_v/vtex.store-graphql/graphiql/v1
> Refact paths and organize API docs

- CHANGELOG.md
- node/resolvers/paths.ts
> Fix vtexId use on paths.ts

- CHANGELOG.md
- node/resolvers/auth/index.ts
Fixed bug in `logout` mutation that didn't log out correctly
https://login--storecomponents.myvtex.com/
> Fix mutation that didn't log out correctly

- CHANGELOG.md
- graphql/types/Benefits.graphql
- node/resolvers/benefits/index.ts
- node/resolvers/catalog/index.ts
- node/resolvers/paths.ts
Benefits Resolver
Products are being complemented with the Benefits which they are associated.
<a href="https://gustavo--storecomponents.myvtex.com/_v/vtex.store-graphql/graphiql/v1">Workspace</a>
```gql
query Product($slug: String) {
product(slug: $slug) {
benefits {
items {
product {
productName
}
discount
minQuantity
}
}
}
}
```
```json
{
"slug": "porsche-911"
}
```
> Benefits Resolver

- CHANGELOG.md
- graphql/schema.graphql
- node/resolvers/auth/index.ts
- node/resolvers/paths.ts
Resolver to provides OAuth authentication.
Access:  https://andre--storecomponents.myvtex.com/
- New feature (a non-breaking change which adds functionality)
> OAuth resolver

- CHANGELOG.md
- graphql/types/Benefits.graphql
- node/resolvers/benefits/index.ts
- Fix circular benefit query
- When executing the query Product with the attribute benefits.items.product, cause a circular request query.
[workspace](https://claudivan3--storecomponents.myvtex.com)
1 - Go to Home Page
2 - Click in a product, the Product Page must be rendered without errors
> Fix circular benefit query

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/index.ts
Another error of undefined reference in kitItems resolver
> Fix kititems undefined error

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/index.ts
Error handling when the product is not found
Better error handling 
[graphiql](https://searchhandler--storecomponents.myvtex.com/_v/vtex.store-graphql@2.20.1/graphiql/v1?variables=%7B%0A%20%20%22slug%22%3A%20%22asdadsa%22%0A%7D&operationName=Product)
> Throw specific error when the product is not found on product resolver in catalog

- CHANGELOG.md
- graphql/types/Session.graphql
- manifest.json
- node/resolvers/catalog/index.ts
Fix syntax error in `Catalog Resolver`
https://public-benefits--storecomponents.myvtex.com/_v/vtex.store-graphql@2.21.1/graphiql/v1
> Fix syntax error in Catalog Resolver

- CHANGELOG.md
- manifest.json
- node/resolvers/session/index.ts
Minor adjusts in session resolvers.
> Minor refact in session resolvers and add docs.

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/index.ts
Remove the second query to the facets resolver.
The value returned by this query wasn't being used, and was a waste of resources.
> Remove unused query to facets in search resolver

- CHANGELOG.md
- manifest.json
- node/resolvers/paths.ts
Get the autocomplete from GoCommerce accounts in the GoCommerce API.
> Fix autocomplete for GoCommerce

- CHANGELOG.md
- graphql/types/Profile.graphql
- manifest.json
The user email has to be passed in fields.
> Change email to be a required field in ProfileInput

- CHANGELOG.md
- manifest.json
- node/resolvers/session/sessionResolver.ts
> Return email in getSession when a new user is logged

- CHANGELOG.md
- manifest.json
- node/dataSources/catalog.ts
- node/index.ts
- node/package.json
- node/routes/catalogProxy.ts
- node/service.json
- node/typings/colossus.d.ts
- node/yarn.lock
Create cacheable catalog proxy
Catalog caching
> Create cacheable catalog proxy

- CHANGELOG.md
- manifest.json
- node/dataSources/catalog.ts
- node/package.json
- node/resolvers/catalog/index.ts
- node/routes/catalogProxy.ts
- node/yarn.lock
If there is no search term, the search query should return an educated error
> Require searchTerm in search query

- CHANGELOG.md
- manifest.json
- node/routes/catalogProxy.ts
Fix URL encoding
Search for products with URL unfriendly characters (`ç`, `ã`, etc) throws an error.
> Fix URL encoding

- CHANGELOG.md
- manifest.json
- node/package.json
- node/routes/catalogProxy.ts
- node/yarn.lock
Fix proxy catalog querystring format
> fix proxy querystring to match catalogs standard

- CHANGELOG.md
- manifest.json
- node/service.json
> Increase max replicas

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/brand.ts
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/slug.ts
```query search($query: String, $map: String, $rest: String, $orderBy: String, $priceRange: String, $from: Int, $to: Int) {
search(query: $query, map: $map, rest: $rest, orderBy: $orderBy, priceRange: $priceRange, from: $from, to: $to) {
titleTag
metaTagDescription
products {
cacheId
categories
productId
productName
linkText
description
brand
link
items {
itemId
name
nameComplete
complementName
sellers {
sellerId
sellerName
commertialOffer {
Price
ListPrice
PriceWithoutDiscount
RewardValue
PriceValidUntil
AvailableQuantity
}
}
}
productClusters {
name
}
}
recordsFiltered
}
}
```
[workspace](https://bruno--boticario.myvtex.com/_v/vtex.store-graphql@2.31.8/graphiql/v1?operationName=search&variables=%7B%0A%20%20%22query%22%3A%20%22dimitri%22%2C%20%0A%20%20%22map%22%3A%20%22b%22%2C%20%0A%20%20 …
> Add titleTag and metaTagDescription in searchs for brand

- CHANGELOG.md
- manifest.json
- node/dataSources/catalog.ts
Fix product by slug search
Catalog API is case-sensitive.
See:
http://boticario.vtexcommercestable.com.br/api/catalog_system/pub/products/search/coffee-woman-seduction-des--colonia-100ml-27704/p 
vs
http://boticario.vtexcommercestable.com.br/api/catalog_system/pub/products/search/Coffee-Woman-Seduction-des--colonia-100ml-27704/p
> Fix product by slug search

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/directives/index.ts
- node/directives/response.ts
- node/index.ts
- node/package.json
- node/resolvers/catalog/index.ts
- node/tsconfig.json
- node/yarn.lock
Use schema directive to set vary response header
> Change hardcoded vary response to schema directive

- CHANGELOG.md
- manifest.json
- node/routes/catalogProxy.ts
It fixes gocommerce catalog requests
Gocommerce API does not respond on http, only https
> Call catalog endpoint with HTTPS

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/calculatedAttachmentsResolver.ts
- node/resolvers/session/sessionResolver.ts
- node/yarn.lock
There are many property of undefined error in the logs. This pr fixes the most common ones
> Fix common property of undefined errors

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
Change search query maxAge to SHORT
> Change search query maxAge to SHORT

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
Change `product` and `products` query maxAge to `SHORT`
> Change product / products query maxAge to SHORT

- CHANGELOG.md
- manifest.json
- node/dataSources/catalog.ts
- node/dataSources/checkout.ts
- node/dataSources/portal.ts
- node/dataSources/session.ts
- node/resolvers/checkout/index.ts
- node/routes/catalogProxy.ts
- node/service.json
Improve store graphql resilience with timeouts
> Improve resilience

- CHANGELOG.md
- manifest.json
- node/dataSources/catalog.ts
- node/dataSources/session.ts
- node/resolvers/profile/profileResolver.ts
- node/routes/catalogProxy.ts
Also stop sending Authorization header to segment incorrectly
> Sanitize url before sending request to catalog and stop considering profile without a token an error

- CHANGELOG.md
- manifest.json
- node/dataSources/catalog.ts
- node/routes/catalogProxy.ts
- node/yarn.lock
Use the catalog proxy instead of consulting the VTEX api directly.
The query doesn't work for gocommerce accounts.
[Workspace](https://lucas2--storecomponents.myvtex.com/eletronicos/d).
> Use catalog proxy for total products query

- CHANGELOG.md
- manifest.json
- node/resolvers/profile/profileResolver.ts
- Fixed `profileResolver` to work for an impersonated customer
> Fixed profileResolver to work for an impersonated customer

- CHANGELOG.md
- manifest.json
- node/service.json
[Temporary Fix] Raise pod memory to 1024
> Raise pod memory to 1024

- CHANGELOG.md
- manifest.json
- node/utils/cookie.ts
> fix typo in cookie name

- CHANGELOG.md
- node/resolvers/profile/fieldResolvers.ts
> Fixing changelog

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Suggestions.graphql
- manifest.json
- node/dataSources/index.ts
- node/dataSources/messages.ts
- node/resolvers/catalog/index.ts
- node/typings.d.ts
This allows for the user to do searches in the language the store is in.  
It translates the result of the search queries and translates the search term
> Translated search

- CHANGELOG.md
- manifest.json
- policies.json
Adds policies.json to allow other apps to call store-graphql
> add policies to allow other apps to call store-graphql

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
Fix queries max age
- [X ] Bug fix (a non-breaking change which fixes an issue)
> Fix queries max age

- CHANGELOG.md
- manifest.json
- node/routes/catalogProxy.ts
> using correct method in catalog proxy

- CHANGELOG.md
- graphql/types/Order.graphql
- Fix transactions in `orders` query.
> Fix transactions in orders query

- .prettierrc
- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Order.graphql
- graphql/types/Profile.graphql
- manifest.json
- node/dataSources/index.ts
- node/dataSources/profile.ts
- node/dataSources/session.ts
- node/directives/withCurrentProfile.ts
- node/package.json
- node/resolvers/document/attachment.ts
- node/resolvers/profile/fieldResolvers.ts
- node/resolvers/profile/index.ts
- node/resolvers/profile/services.ts
- node/resolvers/session/sessionResolver.ts
- node/typings.d.ts
- node/utils/index.ts
- node/yarn.lock
- As the title says, changing  from master-data  to profile-system
> Using profile-system instead of accessing master-data directly

- CHANGELOG.md
- manifest.json
- node/routes/catalogProxy.ts
> Disable head gocommerce

- CHANGELOG.md
- lint.sh
- manifest.json
- node/dataSources/RESTDataSource.ts
- node/dataSources/index.ts
- node/index.ts
- node/package.json
- node/yarn.lock
Removes datasources cache since it was mostly unnused
> Removing cache

- CHANGELOG.md
- graphql/types/OrderForm.graphql
- manifest.json
> add seller field to OrderFormItem

- CHANGELOG.md
- manifest.json
- node/resolvers/checkout/attachmentsHelper.ts
fix break on exito for items with attachments on old format
> filter for composition != null on assemblyOptions resolver

- CHANGELOG.md
- manifest.json
- node/routes/catalogProxy.ts
Fix cookies not being properly sent to search API
Fix cookies not being properly sent to search API
> Fix cookies not being properly sent to search API

- CHANGELOG.md
- manifest.json
- node/resolvers/profile/fieldResolvers.ts
Transform the date given by profile system API to the ISO format.
It was leading to strange behaviours in the UI.
Make a query that uses profile and check if the string is in ISO format.
> Fix profile birthDate to ISO format

- CHANGELOG.md
- manifest.json
- node/resolvers/checkout/sessionManager.ts
Removes errors `Invalid CEP` from checkout API
> Invalid cep

- CHANGELOG.md
- graphql/types/Product.graphql
- node/resolvers/catalog/product.ts
- node/routes/catalogProxy.ts
As the title said 
Access the [GraphiQl](https://highlightsprod--storecomponents.myvtex.com/_v/vtex.store-graphql@2.60.7/graphiql/v1?operationName=Product&variables=%7B%0A%20%20%22slug%22%3A%20%22long-sleeve-shirt%22%0A%7D) and pass the [product query](https://github.com/vtex-apps/store-resources/blob/master/react/queries/product.gql) for slug `shirt`.
> Add specificationGroups in product resolver

- .vtexignore
- as the title says...
- link now is working properly
> Remove yarn.lock from vtexignore

- CHANGELOG.md
- manifest.json
- node/service.json
> Increase min replicas

- CHANGELOG.md
- manifest.json
- node/dataSources/catalog.ts
> Remove __v when calling catalog-api-proxy to have consistent url for improved router cache

- CHANGELOG.md
- graphql/types/Profile.graphql
- manifest.json
- node/resolvers/auth/index.ts
- node/resolvers/paths.ts
- node/resolvers/profile/fieldResolvers.ts
- node/resolvers/profile/services.ts
Add field `lastPasswordUpdate` to profile.
There were no other way to check if a profile has a password or not.
> Add profile last password update

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/product.ts
> Fix type error introduced in Typescript 3.4

- CHANGELOG.md
- manifest.json
- node/dataSources/catalog.ts
- node/index.ts
- node/package.json
- node/yarn.lock
Add 1 retry to catalog api calls
> Fix retries

- CHANGELOG.md
- manifest.json
- node/dataSources/checkout.ts
- node/directives/withCurrentProfile.ts
- node/errors/resolverError.ts
- node/package.json
- node/resolvers/auth/index.ts
- node/resolvers/catalog/index.ts
- node/resolvers/document/attachment.ts
- node/resolvers/headers.ts
- node/resolvers/list/index.ts
- node/resolvers/list/util.ts
- node/resolvers/session/index.ts
- node/yarn.lock
Use errors from https://github.com/vtex/node-vtex-api/pull/130
Improve error log by demoting errors we can't fix to warnings, such as Product Not Found.
> Port to native errors and warnings

- README.md
- graphql/schema.graphql
> Add graphql docs

- CHANGELOG.md
- graphql/types/Facets.graphql
- manifest.json
Remove the required in the `map` field of the `Facets` type.
This field isn't required in the priceRanges.
[Workspace](https://lucas--storecomponents.myvtex.com/decoration).
> Remove required in map field

- CHANGELOG.md
- graphql/types/List.graphql
- manifest.json
- node/resolvers/list/index.ts
- node/resolvers/list/util.ts
As the title says.
This PR is associated to [this one](https://github.com/vtex-apps/wishlist/pull/4).
https://waza--storecomponents.myvtex.com/_v/vtex.store-graphql@2.67.1/graphiql/v1
> Add isEditable field to list

- CHANGELOG.md
- manifest.json
- node/dataSources/checkout.ts
The current checkout API needs a bigger timeout to work with HUGE carts. This pr gives the extra time needed for the checkout api to answer
> Checkout Timeout

- CHANGELOG.md
- graphql/types/ProductSearch.graphql
- manifest.json
- node/resolvers/catalog/index.ts
As the title says
[Test here](https://meta--storecomponents.myvtex.com/_v/vtex.store-graphql@2.70.0/graphiql/v1?operationName=search&query=query%20search%20%7B%0A%20%20productSearch(query%3A%20%22bmw%22%2C%20map%3A%22b%22)%20%7B%0A%20%20%20%20titleTag%0A%20%20%20%20metaTagDescription%0A%20%20%20%20products%20%7B%0A%20%20%20%20%20%20cacheId%0A%20%20%20%20%20%20categories%0A%20%20%20%20%20%20productId%0A%20%20%20%20%20%20description%0A%20%20%20%20%20%20productName%0A%20%20%20%20%20%20linkText%0A%20%20%20%20%20%20brand%0A%20%20%20%20%20%20link%0A%20%20%20%20%20%20items%20%7B%0A%20%20%20%20%20%20%20%20itemId%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20nameComplete%0A%20%20%20%20%20%20%20%20complementName%0A%20%20%20%20%20%20%20%20ean%0A%20%20%20%20%20%20%20%20referenceId%20%7B%0A% …
> Add titleTag and metaTagDescription in productSearch query

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/dataSources/catalog.ts
https://app.clubhouse.io/vtex-dev/story/10619/add-prop-to-choose-not-to-show-unavailable-products-on-search-result
Before:
https://dev--invictastores.myvtex.com/impact-cases
After:
https://fidelis--invictastores.myvtex.com/impact-cases
> Use segment salesChannel for search queries.

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Facets.graphql
- graphql/types/Product.graphql
- manifest.json
- node/resolvers/catalog/category.ts
- node/resolvers/catalog/facets.ts
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/product.ts
- node/utils/ioMessage.ts
Makes translation to work with Categories and Products
> Translate Categories and Products

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/facets.ts
https://fidelis--invictastores.myvtex.com/watches/invicta/S1%20RALLY
https://fidelis--invictastores.myvtex.com/watches/invicta/VENOM
> slugify facets when checking if is selected:

- graphql/schema.graphql
- graphql/types/Profile.graphql
> Add doc to the profile queries and mutations.

- CHANGELOG.md
- graphql/types/Facets.graphql
- manifest.json
This pr adds some fields back to facets due to some stores using these ghost fields
> Fix facets compatibility

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/resolvers/catalog/index.ts
- node/typings/Catalog.ts
https://fidelis--invictastores.myvtex.com/
> add hideUnavailableItems parameter to facets query

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/clients/checkout.ts
> fix checkout client routes

- CHANGELOG.md
- manifest.json
This is a version bump to make store-graphql to gain the newly exported messages policy from builder-hub
> Release v2.74.3

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/utils.ts
https://fidelis--boticario.myvtex.com/_v/vtex.store-graphql@2.75.1/graphiql/v1?query=query%20%7B%0A%20%20searchContextFromParams(brand%3A%20%22make-b%22)%20%7B%0A%20%20%20%20contextKey%0A%20%20%20%20brand%0A%20%20%7D%0A%7D
> compare catalogSlugify and old slugify methods on brand search

- CHANGELOG.md
- manifest.json
- node/globals.ts
- node/resolvers/document/index.ts
> Throw error in updateDocument resolver if `id` field is undefined/null

- CHANGELOG.md
- manifest.json
- node/globals.ts
- node/resolvers/list/index.ts
- node/utils/object.ts
As the title says.
The lists mutations were not working, so it was not able to add a product to the wishlist.
[Click here to access the workspace.](https://waza--storecomponents.myvtex.com/)
> Fix lists mutations

- CHANGELOG.md
- manifest.json
- node/dataSources/profile.ts
- node/directives/withCurrentProfile.ts
- node/resolvers/profile/services.ts
- ditto.
- log in with an email that has '+'.
>  Fix profile query for emails containing '+'

- CHANGELOG.md
- manifest.json
- node/clients/catalog.ts
- node/clients/index.ts
- node/dataSources/index.ts
- node/globals.ts
- node/index.ts
- node/resolvers/benefits/index.ts
- node/resolvers/catalog/category.ts
- node/resolvers/catalog/facets.ts
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/productSearch.ts
- node/resolvers/catalog/recommendation.ts
- node/resolvers/catalog/search.ts
- node/resolvers/catalog/sku.ts
- node/resolvers/catalog/utils.ts
- node/resolvers/list/index.ts
- node/resolvers/list/util.ts
> Port catalog datasource to client

- CHANGELOG.md
- node/resolvers/profile/index.ts
https://fidelis--storecomponents.myvtex.com/
> pass current profile object to client on subscribe newsletter mutation

- CHANGELOG.md
- node/resolvers/catalog/product.ts
- node/resolvers/catalog/utils.ts
https://fidelis--samsungar.myvtex.com/_v/vtex.store-graphql@2.83.3/graphiql/v1?query=query%20%7B%0A%20%20product(slug%3A%20%22galaxy-s10%22)%20%7B%0A%20%20%20%20categoryTree%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20href%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20categories%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20slug%0A%20%20%20%20children%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20slug%0A%20%20%20%20%20%20children%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20slug%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20children%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20slug%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D …
> look for category in map

- CHANGELOG.md
- node/resolvers/catalog/searchBreadcrumb.ts
https://fidelis2--alssports.myvtex.com/_v/vtex.store-graphql@2.84.0/graphiql/v1?query=query%20%7B%0A%20%20productSearch(query%3A%22the%2520north%2520face%22%2C%20map%3A%22ft%22)%20%7B%0A%20%20%20%20breadcrumb%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20href%0A%20%20%20%20%7D%0A%20%20%20%20%23%20products%20%7B%0A%20%20%20%20%23%20%20%20productName%0A%20%20%20%20%23%20%7D%0A%20%20%7D%0A%20%20teste%3A%20productSearch(query%3A%22the%2520north%2520face%2FClothing%2FHoodies---Sweatshirts%22%2C%20map%3A%22ft%2Cc%2Cc%22)%20%7B%0A%20%20%20%20breadcrumb%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20href%0A%20%20%20%20%7D%0A%20%20%20%20%23%20products%20%7B%0A%20%20%20%20%23%20%20%20productName%0A%20%20%20%20%23%20%7D%0A%20%20%7D%0A%20%20teste2%3A%20productSearch(query%3A%22The-North-Face% …
> decore unit name on search breadcrumb, small code improvements

- CHANGELOG.md
- graphql/types/OrderForm.graphql
Fix scalar type attribute in orderForm -> orderFormItems -> PriceTags -> rawValue
Return the value without problems
Run the orderForm query normally
> Fix interger to float in price tags atribute

- CHANGELOG.md
- node/globals.ts
- node/resolvers/profile/fieldResolvers.ts
- node/resolvers/profile/services.ts
Fixes geocoordinates field in profile
> Fixes geocoordinates on profile

- CHANGELOG.md
- graphql/types/Suggestions.graphql
- node/resolvers/catalog/autocomplete.ts
as title says
---|---
_ | Bug fix 
> Adds productId to suggestions api

- CHANGELOG.md
- node/resolvers/catalog/index.ts
> uses slug in gocommerce

- CHANGELOG.md
- node/resolvers/catalog/searchBreadcrumb.ts
- node/typings/Catalog.ts
https://fidelis--parquedpedro.myvtex.com/c/tng
---|---
_ | Bug fix 
> search for seller name on products

- CHANGELOG.md
- node/globals.ts
- node/resolvers/profile/fieldResolvers.ts
- node/resolvers/profile/services.ts
The information saved using `updateProfile` mutation was not complete, since some properties were not using the correct name that the API expects to read. The same happened with the `profile` query.
Use the following workspace and execute the `updateProfile` mutation changing corporate fields, like: `corporateDocument`, `isCorporate` and `tradeName`.
[Workspace](https://arthurepc--recorrenciaqa.myvtex.com/_v/vtex.store-graphql@2.90.2/graphiql/v1?variables=%7B%0A%20%20%22profile%22%3A%20%7B%0A%20%20%20%20%22birthDate%22%3A%20%221996-04-25T00%3A00%3A00Z%22%2C%0A%20%20%20%20%22businessPhone%22%3A%20null%2C%0A%20%20%20%20%22corporateDocument%22%3A%20%2297.913.462%2F0001-31%22%2C%0A%20%20%20%20%22corporateName%22%3A%20%22razao%20teste%22%2C%0A%20%20%20%20%22document%22%3A%20%22381.995.180-65%22 …
> Fix corporate info

- CHANGELOG.md
- manifest.json
> Release v2.90.8

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/SiteConfigs.graphql
- node/clients/index.ts
- node/clients/portal.ts
- node/resolvers/index.ts
- node/resolvers/portal/index.ts
The My Account app needs the google maps key to show the address form with geolocation.
[Workspace](https://arthur--fstudio.myvtex.com/_v/vtex.store-graphql@2.87.1/graphiql/v1?query=query%20%7B%0A%09siteConfigs%20%7B%0A%20%20%20%20geolocation%0A%20%20%20%20googleMapsApiKey%0A%20%20%7D%0A%7D)
---|---
_ | Bug fix 
> Add siteConfigs query

- graphql/schema.graphql
- graphql/types/Category.graphql
- graphql/types/Facets.graphql
- graphql/types/Product.graphql
- graphql/types/ProductSearch.graphql
- graphql/types/Suggestions.graphql
> Uses translatable directive

- CHANGELOG.md
- node/clients/checkout.ts
- node/globals.ts
- node/resolvers/catalog/autocomplete.ts
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/itemMetadataPriceTableItem.ts
- node/resolvers/checkout/assemblyOptionItem.ts
- node/resolvers/checkout/attachmentsHelper.ts
- node/resolvers/checkout/index.ts
- node/resolvers/checkout/orderFormItem.ts
- node/typings/Checkout.ts
- node/typings/ItemMetadata.ts
just more types
https://fidelis--storecomponents.myvtex.com
or
https://fidelis--storecomponents.myvtex.com/_v/vtex.store-graphql@2.93.1/graphiql/v1
---|---
_ | Bug fix 
> type order form, use it

- CHANGELOG.md
- graphql/types/Product.graphql
- node/resolvers/catalog/product.ts
- node/typings/Catalog.ts
The `GiftSkuIds` field is missing in the` Offer` schema and it is used for gift listing.
This [workspace](https://fixgraphql--tbb.myvtex.com/_v/vtex.store-graphql@2.93.2/graphiql/v1?operationName=Product&query=query%20Product(%24slug%3A%20String)%20%7B%0A%20%20product(slug%3A%20%24slug)%20%7B%0A%20%20%20%20productId%0A%20%20%20%20productName%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20sellers%20%7B%0A%20%20%20%20%20%20%20%20commertialOffer%20%7B%0A%20%20%20%20%20%20%20%20%20%20GiftSkuIds%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22slug%22%3A%20%22miss-dior-feminino-eau-de-toilette-801034-p%22%0A%7D) is linked on the branch from Pull Request and can bring the gifts associated with this …
> Add `GiftSkuIds` field to the `Offer` schema

- CHANGELOG.md
- node/resolvers/list/index.ts
As the title says.
[Click here to access the workspace.](https://vitoria--storecomponents.myvtex.com/)
---|---
✔️ | Bug fix 
This PR is related to these PRs:
https://github.com/vtex-apps/wishlist/pull/22
https://github.com/vtex-apps/login/pull/137
> listsByOwner query not returning the lists updated values

- CHANGELOG.md
- graphql/types/OrderForm.graphql
- node/typings/Checkout.ts
Add new fields so we can fill the analytics events.
[Workspace](https://breno--storecomponents.myvtex.com/)
---|---
_ | Bug fix 
> Add new item fields

- CHANGELOG.md
- graphql/types/ItemMetadata.graphql
- graphql/types/OrderForm.graphql
- node/clients/checkout.ts
- node/resolvers/catalog/itemMetadata.ts
- node/resolvers/catalog/itemMetadataPriceTableItem.ts
- node/resolvers/catalog/itemMetadataUnit.ts
- node/resolvers/checkout/assemblyOptionItem.ts
- node/resolvers/checkout/attachmentsHelper.ts
- node/resolvers/checkout/index.ts
- node/resolvers/checkout/orderFormItem.ts
- node/typings/Catalog.ts
- node/typings/Checkout.ts
- node/typings/ItemMetadata.ts
1-Try to add a item, make sure everything works fine
2-Trust me it works with recursive assembly options
https://fidgraphql--storecomponents.myvtex.com/
> implement recursive assembly options add logic

- CHANGELOG.md
- node/resolvers/catalog/itemMetadataPriceTableItem.ts
https://show--delivery.myvtex.com/_v/private/vtex.store-graphql@2.97.0/graphiql/v1
https://show--delivery.myvtex.com/_v/private/vtex.store-graphql@2.97.0/graphiql/v1?query=query%20%7B%0A%20%20product(slug%3A%20%22combo-sandwich%22)%20%7B%0A%20%20%20%20itemMetadata%20%7B%0A%20%20%20%20%20%20priceTable%20%7B%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%20%20values%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20assemblyId%0A%20%20%20%20%20%20%20%20%20%20price%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
> try to use familyMinimum on multiple assembly simulation

- CHANGELOG.md
- graphql/types/Profile.graphql
- node/resolvers/session/sessionResolver.ts
- node/typings/Session.ts
Make it possible to create components that queries priceTable the current session is on.
[Workspace](https://breno--alssports.myvtex.com/billab-rashguard-die-cut-lf-ss/p)
---|---
_ | Bug fix 
> Feature priceTables

- CHANGELOG.md
- graphql/types/OrderForm.graphql
Get unitMultiplier field in query orderForm
I need get unitMultiplier field in orderForm
added unitMultiplier field inside item in orderForm
---|---
_ | Bug fix 
✔️_ | New feature 
> Order form item

- CHANGELOG.md
- graphql/types/Product.graphql
- node/resolvers/catalog/sku.ts
- node/typings/Catalog.ts
Retrieve product videos from catalog.
https://augusto--storecomponents.myvtex.com/work-shirt/p
---|---
_ | Bug fix 
✔️| New feature 
> Add field videos to product items

- CHANGELOG.md
- graphql/types/Brand.graphql
- graphql/types/Category.graphql
- graphql/types/Product.graphql
- node/clients/catalog.ts
- node/directives/withCurrentProfile.ts
- node/globals.ts
- node/package.json
- node/resolvers/catalog/brand.ts
- node/resolvers/catalog/category.ts
- node/resolvers/catalog/product.ts
- node/resolvers/catalog/sku.ts
- node/resolvers/catalog/utils.ts
- node/typings/Catalog.ts
- node/utils/ioMessage.ts
- node/yarn.lock
Add more translatable fields for catalog members inside `store-graphql` - `Messages`.
After the discussions with Bacelar and Daniel we defined the final fields to be translated as: 
(after the arrow I let how each of these fields are being represented in code)
- Name   ->   `name`
- Title   ->   `titleTag`
- MetaTagDescription   ->   `metaTagDescription`
- Name   ->   `name`
- Title   ->   `title`
- MetaTagDescription    ->   `metaTagDescription` 
- NameComplete   ->   `nameComplete`
- ProductName   ->   `productName`
- ProductDescription   ->   `productDescription`
- SkuName   ->   `name`
- BrandName   ->    `brandName`
- SkuSpecifications[]   ->   `skuSpecifications`
- FieldName 
- FieldValues[]
- ProductSpecifications[]   ->   `productSpecifications`
- FieldName 
- FieldValues[]
- Name …
> More translatable fields in providers

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/checkout.ts
- node/resolvers/session/index.ts
- node/yarn.lock
Make impersonate and depersonify mutations to change OrderForm.
The change consists in changing the email in the orderForm when the user is impersonated. When depersonify, we forget the user in the orderForm.
Workspace test: [storecomponents/breno](https://breno--storecomponents.myvtex.com/)
Your user should have Televendas roles in License Manager.
---|---
✔️ | Bug fix 
> Fix impersonation

- CHANGELOG.md
- node/resolvers/catalog/category.ts
- node/resolvers/catalog/searchBreadcrumb.ts
- node/yarn.lock
Removes old way of routing and uses canonical routes
Check if breadcrumbs links are without `/d` in the end.
---|---
_ | Bug fix 
> Removes old  routing

- node/service.json
> Request more memory to avoid restarts due to mem starvation

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/ProductSearch.graphql
- node/resolvers/catalog/index.ts
- node/yarn.lock
https://fidteste--exitocol.myvtex.com/moda-y-accesorios/moda-nina/exterior-nina
view-source:https://fidteste--exitocol.myvtex.com/moda-y-accesorios/moda-nina/exterior-nina
see it returns with title as the name of the category from ssr
> search metadata query

- CHANGELOG.md
- node/resolvers/catalog/index.ts
https://fidelis--tbb.myvtex.com/perfumes
> throw bad request if facets has undefined

- CHANGELOG.md
- node/resolvers/catalog/index.ts
> Throw user input error if to parameter is greater than 2500 in search

- CHANGELOG.md
- node/resolvers/checkout/index.ts
- node/typings/Checkout.ts
https://fidelis--boticario.myvtex.com/
> filter null marketing tags

- CHANGELOG.md
- graphql/types/Profile.graphql
[Reference](https://www.apollographql.com/docs/apollo-server/data/file-uploads/)
> Revert scalar Upload since that comes from Apollo Server

- .vtexignore
- CHANGELOG.md
- graphql/types/ItemMetadata.graphql
- graphql/types/OrderForm.graphql
- node/package.json
- node/resolvers/checkout/attachmentsHelper.ts
- node/tsconfig.json
- node/typings/Checkout.ts
- node/yarn.lock
1. Open [Workspace](https://breno--storecomponents.myvtex.com/star-color-top/p)
2. Choose a Font
3. Check Glossy Print
4. Click Add to cart
5. Go to the checkout page
Type in the console: `vtexjs.checkout.orderForm.items[0].assemblies[0]`
You should see the assemblies are added:
---|---
_ | Bug fix 
> Handle Assembly Options' Input Values

- CHANGELOG.md
- node/resolvers/profile/fieldResolvers.ts
Bad geolocation type
https://geolocation--exitocol.myvtex.com
---|---
_ | Bug fix 
> on address type use geocoordinates and geocoordinate

- graphql/schema.graphql
- graphql/types/Logistics.graphql
- graphql/types/OrderForm.graphql
- graphql/types/Session.graphql
- node/clients/checkout.ts
- node/resolvers/checkout/checkoutSLA.ts
- node/resolvers/checkout/index.ts
- node/resolvers/index.ts
- node/resolvers/logistics/fieldResolvers.ts
- node/resolvers/session/index.ts
- node/resolvers/session/sessionPickup.ts
- node/resolvers/session/sessionResolver.ts
- node/typings/Checkout.ts
Implement queries used by the component `pickup-availability` that accept coordinates and a SKU and answers with the pickup points where you can pickup that item.
https://storek3--delivery.myvtex.com/_v/private/vtex.store-graphql@2.106.0/graphiql/v1?query=%23%20query%20%7B%0A%23%20%20%20skuPickupSLAs(itemId%3A%225103%22%2C%20seller%3A%221%22%2C%20country%3A%22BRA%22%2C%20lat%3A%22-22.944370%22%2C%20long%3A%22-43.182553%22)%20%7B%0A%23%20%20%20%20%20id%0A%23%20%20%20%20%20shippingEstimate%0A%23%20%20%20%20%20pickupStoreInfo%20%7B%0A%23%20%20%20%20%20%20%20friendlyName%0A%23%20%20%20%20%20%20%20address%20%7B%0A%23%20%20%20%20%20%20%20%20%20street%0A%23%20%20%20%20%20%20%20%7D%0A%23%20%20%20%20%20%7D%0A%23%20%20%20%7D%0A%23%20%7D%0A%0Aquery%20%7B%0A%20%20skuPickupSLA(itemId%3A%225103%22%2C%20 …
> implement sku pickup slas queries

- CHANGELOG.md
- graphql/types/ItemMetadata.graphql
- graphql/types/OrderForm.graphql
- node/package.json
- node/resolvers/catalog/index.ts
- node/yarn.lock
https://fidelis--lily.myvtex.com?cultureInfo=es-ES
add a product with name translated to the cart. Make sure the name continues translated in the cart.
---|---
_ | Bug fix 
> make name and skuName in orderform item be translatable

- CHANGELOG.md
- graphql/schema.graphql
> deprecation notices

- node/clients/catalog.ts
- node/clients/checkout.ts
- node/clients/oms.ts
https://protected--storecomponents.myvtex.com/
> protect against null tokens

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Profile.graphql
- node/clients/catalog.ts
- node/resolvers/profile/index.ts
- node/typings/Catalog.ts
B2B scenarios where a Trade Policy is closed.
Check description of: 
https://github.com/vtex-apps/challenge-login/pull/1
---|---
_ | Bug fix 
Related https://github.com/vtex-apps/challenge-login/pull/1
> Add new query to check if user can access a sales channel

- README.md
- docs/README.md
- manifest.json
Hey there!
Sorry to interrupt your developing flow,
Please take a while to approve this PR and release a version for this :heart:
You'll help us create a beautiful documentation tool.
Any questions go ahead and reach me! :smile::rocket:
> Docs structure migration

- CHANGELOG.md
- node/package.json
- node/resolvers/document/index.ts
- node/yarn.lock
adapt to new builder hub
---|---
_ | Bug fix 
> adapt to ts 3.7

- graphql/schema.graphql
- graphql/types/OrderForm.graphql
- node/__mocks__/orderForm.ts
- node/__tests__/checkout/index.test.ts
- node/package.json
- node/resolvers/checkout/index.ts
- node/yarn.lock
> create utm params vars

- CHANGELOG.md
- node/resolvers/catalog/product.ts
https://fidelis--biscoind.myvtex.com/
O código foi copiado do search-graphql. Its production proven already
---|---
_ | Bug fix 
> remove call to categories/tree API on product resolvers

- CHANGELOG.md
- node/resolvers/checkout/index.ts
> log when orderformids are different

- CHANGELOG.md
- node/clients/logistics.ts
- node/resolvers/checkout/index.ts
- node/resolvers/logistics/fieldResolvers.ts
- node/resolvers/logistics/types.ts
- node/typings/Checkout.ts
https://fidelis--delivery.myvtex.com/_v/private/vtex.store-graphql@2.113.6/graphiql/v1?query=query%20%7B%0A%20%20skuPickupSLAs(itemId%3A%20%22501%22%2C%20seller%3A%221%22%2C%20lat%3A%20%22-22.9447671%22%2C%20long%3A%22-43.18252929999999%22%2C%20country%3A%22BRA%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20shippingEstimate%0A%20%20%20%20pickupStoreInfo%20%7B%0A%20%20%20%20%20%20friendlyName%0A%20%20%20%20%20%20address%20%7B%0A%20%20%20%20%20%20%20%20street%0A%20%20%20%20%20%20%20%20number%0A%20%20%20%20%20%20%20%20cacheId%0A%20%20%20%20%20%20%20%20addressId%0A%20%20%20%20%20%20%20%20complement%0A%20%20%20%20%20%20%20%20neighborhood%0A%20%20%20%20%20%20%20%20country%0A%20%20%20%20%20%20%20%20state%0A%20%20%20%20%20%20%20%20geoCoordinates%0A%20%20%20%20%20%20%20%20postalCode%0A%20%20%20%20%20%20% …
> make pickupSLAs query return unavailable pickups

- CHANGELOG.md
- node/clients/logistics.ts
https://fidelis--worldwidegolf.myvtex.com/_v/private/vtex.store-graphql@2.113.7/graphiql/v1?query=query%20%7B%0A%20%20nearPickupPoints(lat%3A%2233.7300478%22%2C%20long%3A%22-117.8347145%22%2C%20maxDistance%3A100)%20%7B%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20friendlyName%0A%20%20%20%20%20%20distance%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
---|---
_ | Bug fix 
> fix nearPickupPoints route

- CHANGELOG.md
- graphql/types/OrderForm.graphql
- node/resolvers/checkout/orderFormItem.ts
- node/typings/Checkout.ts
https://fidelis--worldwidegolf.myvtex.com/_v/private/vtex.store-graphql@2.113.8/graphiql/v1?query=query%20%7B%0A%20%20orderForm%20%7B%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20hasAttachment%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
---|---
_ | Bug fix 
> implement hasAttachment resolver

- graphql/schema.graphql
- graphql/types/Document.graphql
- node/resolvers/document/index.ts
Fix identation, and linting in some files, preparing for my next PR
---|---
_ | Bug fix 
✔️ | Technical improvements
> #trivial Lint

- CHANGELOG.md
- graphql/schema.graphql
- node/resolvers/profile/index.ts
https://app.clubhouse.io/vtex/story/31587/create-an-opt-in-for-newsletter-in-my-profile
1. See what is the value before, using the [profile query](https://newsletter--storecomponents.myvtex.com/_v/private/vtex.store-graphql@2.113.5/graphiql/v1?variables=%7B%0A%20%20%22customFields%22%3A%20%22isNewsletterOptIn%22%0A%7D&operationName=Profile&query=query%20Profile%20(%24customFields%3A%20String)%7B%0A%20%20profile%20(customFields%3A%20%24customFields)%20%7B%0A%20%20%20%20customFields%7B%0A%20%20%20%20%20%20key%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A).
2. Change it, using the [subscribeNewsletter mutation](https://newsletter--storecomponents.myvtex.com/_v/private/vtex.store-graphql@2.113.5/graphiql/v1?variables=%7B%0A%20%20%22email%22%3A%20%22bianca.villar%40vtex.com.b …
> Add optional param

- CHANGELOG.md
- node/resolvers/checkout/orderFormItem.ts
https://fidelis--tbb.myvtex.com/mascara-lee-stafford-hair-growth-800321-p/p?skuId=4277
---|---
_ | Bug fix 
> make order form item image url use https

- CHANGELOG.md
- graphql/schema.graphql
Adds scope private to mutations
---|---
_ | Bug fix 
> Add scope private

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/profile.ts
- node/package.json
- node/resolvers/profile/index.ts
- node/resolvers/profile/services.ts
- node/yarn.lock
- I need the recently added addressId.
- log in to: 
- execute: https://storev1--recorrenciaqa.myvtex.com/_v/private/vtex.store-graphql@2.122.1/graphiql/v1?query=mutation%20SaveAddress(%24address%3A%20AddressInput!)%20%7B%0A%20%20address%3A%20saveAddress(address%3A%20%24address)%20%7B%0A%20%20%20%20id%0A%20%20%20%20cacheId%0A%20%20%7D%0A%7D&operationName=SaveAddress&variables=%7B%0A%20%20%22address%22%3A%20%7B%0A%20%20%20%20%22addressType%22%3A%20%22residential%22%2C%0A%20%20%20%20%22city%22%3A%20%22Belo%20Horizonte%22%2C%0A%20%20%20%20%22country%22%3A%20%22BRA%22%2C%0A%20%20%20%20%22geoCoordinates%22%3A%20%5B-43.93063990000002%2C%20-19.935001%5D%2C%0A%20%20%20%20%22neighborhood%22%3A%20%22Savassi%22%2C%0A%20%20%20%20%22number%22%3A%20%22216%22%2C%0A%20%20%20%20%22postalCode%22%3A%20%22301 …
> Add saveAddress mutation

- CHANGELOG.md
- node/resolvers/checkout/index.ts
> log updateOrderFormMarketingData

- CHANGELOG.md
- graphql/types/Shipping.graphql
To develop a new app related to the delivery options visible on the shelf, we need the Pickup information to the shipping simulate.
Before that, while linking I got an building error, that is fixed too
[Test here](https://wender--sandboxusdev.myvtex.com/_v/private/vtex.store-graphql@2.127.0/graphiql/v1?query=query%20getSimulaltion(%24items%3A%20%5BShippingItem%5D%2C%20%24postalCode%3A%20String%2C%20%24country%3A%20String)%20%7B%0A%20%20shipping(items%3A%20%24items%2C%20postalCode%3A%20%24postalCode%2C%20country%3A%20%24country)%20%7B%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20availability%0A%20%20%20%20%7D%0A%20%20%20%20logisticsInfo%20%7B%0A%20%20%20%20%20%20selectedSla%0A%20%20%20%20%20%20slas%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20price%0A%20%20%20%20%20%20%20 …
> Adding pickupStoreInfo to the ShippingSLA

- CHANGELOG.md
- graphql/types/Logistics.graphql
Have the additionalInfo message available in the pickupPoint query
https://leo--iocea.myvtex.com/calca-de-moletom-infantil-jogger-azul-marinho-9799877-azul_marinho/p
Here's a video to show where it is the functionality
https://www.loom.com/share/8f9cefa7df854e5ba9fdfd03d3485135
---|---
_ | Bug fix 
> `instructions` to the `PickupPoint` type

- CHANGELOG.md
- graphql/types/Profile.graphql
- Login  https://cabaceiras--recorrenciacharlie.myvtex.com/ with `assinaturasqa@mailinator.com`
- Escape profile Inputs
[Workspace](https://cabaceiras--recorrenciacharlie.myvtex.com/_v/private/vtex.store-graphql@2.136.3/graphiql/v1?query=query%20Get%20%7B%0A%20%20profile%20%7B%0A%20%20%20%20email%0A%20%20%20%20firstName%0A%20%20%20%20lastName%0A%20%20%7D%0A%7D%0A%0Amutation%20Update(%24firstName%3A%20String!%2C%20%24lastName%3A%20String!%2C%20%24email%3A%20String!)%20%7B%0A%20%20updateProfile(fields%3A%20%7BlastName%3A%20%24lastName%2C%20email%3A%20%24email%2C%20firstName%3A%20%24firstName%7D)%20%7B%0A%20%20%20%20firstName%0A%20%20%20%20lastName%0A%20%20%20%20email%0A%20%20%7D%0A%7D%0A%0Amutation%20UpdateAddress(%24addressId%3A%20String%2C%20%24addressFields%3A%20AddressInput)%20%7B%0A%20% …
> Sanitize profile inputs

- CHANGELOG.md
- node/resolvers/profile/services.ts
The object being checked wasn't the correct one. So, all checks were false for this case. Thus, no cards were displayed.
[Workspace](https://arthur--recorrenciaqa.myvtex.com/)
> Fix parsedPaymentData nullability check

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Product.graphql
- node/clients/checkout.ts
- node/resolvers/checkout/index.ts
- node/typings/Checkout.ts
- node/utils/simulation.ts
1. We were not calculating the `commertialOffer.price` properly. We were missing the `unitmultiplier`.
2. We were not sending utmi info to the simulation call. The same way we did [here](https://github.com/vtex-apps/search-resolver/pull/220)
[Workspace](https://hiago--storecomponents.myvtex.com/)
> fix price and add utmi campaign

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Product.graphql
- node/clients/checkout.ts
- node/resolvers/checkout/index.ts
- node/typings/Checkout.ts
- node/utils/simulation.ts
> Revert #546 

- CHANGELOG.md
- node/clients/checkout.ts
- node/clients/index.ts
- node/resolvers/checkout/index.ts
> Fix broken orderForms with app ID in email

- CHANGELOG.md
- node/clients/checkout.ts
- node/clients/index.ts
- node/resolvers/checkout/index.ts
> Attempt to clear orderForm profile when email is app ID

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Product.graphql
- node/clients/PvtCheckout.ts
- node/clients/index.ts
- node/resolvers/checkout/index.ts
- node/typings/Checkout.ts
- node/utils/simulation.ts
[Before](https://thalyta--exitocol.myvtex.com)
[After](https://thalyta1--exitocol.myvtex.com)
> Create a new checkout client to simulation

- CHANGELOG.md
- manifest.json
- node/dataSources/identity.ts
- node/directives/withCurrentProfile.ts
As the title says and changes the identity API
[Workspace](https://brasileiro--storecomponents.myvtex.com/)
> Add logs to withCurrentProfile directive, changes identity API

- CHANGELOG.md
- graphql/schema.graphql
- node/directives/authorizationMetrics.ts
- node/directives/index.ts
- node/service.json
https://vtex.slack.com/archives/C90SGTR6U/p1636980322082400
> Adding auth logs to graphql

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/profile.ts
- node/directives/withCurrentProfile.ts
- node/resolvers/profile/index.ts
- node/resolvers/profile/services.ts
This reverts commit 2bd9197d840d77e2a3acd1a29956f0a8107a0e52, reversing
changes made to 7ed55ea945ef423c02acdc0b67447fb5e5d9c9f3.
[Workspace](Link goes here!)
> Revert "Merge pull request #583 from vtex-apps/fix/account"

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/profile.ts
- node/directives/withCurrentProfile.ts
- node/resolvers/profile/index.ts
- node/resolvers/profile/services.ts
Allow back the call center operations on the user profile.
[Workspace](Link goes here!)
> Check if user is call center operator

- CHANGELOG.md
- manifest.json
> Release v2.149.2

- CHANGELOG.md
- node/package.json
- node/yarn.lock
Upgrade `ua-parser-js` version to latest to avoid hijacked versions (https://github.com/faisalman/ua-parser-js/issues/536)
Go to [this workspace](https://rafaprtest--loginstore.myvtex.com/account#/authentication/login-sessions), log in with some devices and check that the device type, browser and OS are informed correctly
> Chore/idcs 847/update ua parser

- CHANGELOG.md
- manifest.json
- node/clients/index.ts
- node/clients/profile/index.ts
- node/clients/profile/profileV2.ts
- node/clients/profile/profileV2EU.ts
- node/clients/profile/profileV2US.ts
This PR changes the way we access the new Profile System using Janus to decide where to go to.
Access the Workspace and use My Accounts
[Workspace](https://piieu--qastoreeu.myvtex.com/)
Related to #596
> Profile System PII: Using correct region when it is an EU account

- CHANGELOG.md
- node/utils/simulation.ts
We had to deprecate v2.152.1 of this app, so this PR is just removing the changes introduced by the original PR that was used to release that version.
> Revert changes from PR #604

- node/yarn.lock
Reverts vtex-apps/store-graphql#613
> Revert "Bump y18n from 4.0.0 to 4.0.3 in /node"

- CHANGELOG.md
- graphql/types/Product.graphql
- node/resolvers/checkout/index.ts
> add error to the simulation response

- CHANGELOG.md
- node/utils/cookie.ts
Order Form Id on Checkout 
---|---
✔️ | Bug fix 
> fix: force http only

- CHANGELOG.md
- graphql/types/Payment.graphql
These props are already available at Profile System, this PR is enabling them to be used by stores clients
[Workspace](https://krro--gatewayqa.myvtex.com/_v/private/vtex.store-graphql@2.164.0/graphiql/v1?operationName=Payments&query=query%20Payments%20%7B%0A%20%20profile%20%7B%0A%20%20%20%20cacheId%0A%20%20%20%20userId%0A%20%20%20%20email%0A%20%20%20%20payments%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20paymentSystem%0A%20%20%20%20%20%20cardNumber%0A%20%20%20%20%20%20isExpired%0A%20%20%20%20%20%20expirationDate%0A%20%20%20%20%20%20accountStatus%0A%20%20%20%20%20%20address%20%7B%0A%20%20%20%20%20%20%20%20addressId%3A%20id%0A%20%20%20%20%20%20%20%20addressType%0A%20%20%20%20%20%20%20%20city%0A%20%20%20%20%20%20%20%20complement%0A%20%20%20%20%20%20%20%20country%0A%20%20%20%20%20%20%20%2 …
> :label: Add `isExpired`, `expirationDate` and `accountStatus` to `profile` query

- CHANGELOG.md
- node/clients/profile/profileV1.ts
* Update logic to delete user address
* `vtex link`
> chore: update logic to delete user address

- .vtex/catalog-info.yaml
This pull request adds a **Backstage entity metadata file** to this repository so that the component can be added to the [Dark Kitchen software catalog](https://darkkitchen.vtex.com).
After this pull request is merged, the component will become available.
For more information, read an [overview of the Backstage software catalog](https://backstage.io/docs/features/software-catalog/).
> Add .vtex/catalog-info.yaml config file
