vtex-apps/store-graphql

- service/resolvers/catalog/fieldsResolver.ts
a resolver were receiving the ioContext property as account
so, in the previous versions I ended up treating the variables inconsistently.
But my previous changes (0.0.27 and 0.0.28) embraced more endpoints and I did not test the crossSelling properly.
Now everything is fixed due to @firstdoit noticing it was not working well with our shelf example https://github.com/vtex-apps/fetch-from-store-graphql
> resolve parameters were incongruous

- masterdata/schema/Query.gql
- masterdata/schema/types/Brand.gql
- masterdata/schema/types/Category.gql
- service/package.json
- service/resolvers/catalog/fieldsResolver.ts
- service/resolvers/catalog/index.ts
- service/resolvers/checkout/index.ts
- service/resolvers/headers.ts
- service/resolvers/httpResolver.ts
- service/resolvers/paths.ts
- service/resolvers/profile/profileResolver.ts
- service/service.json
Iago received a complaint via Facebook about a user trying to access category query.
That made me realize neither brand, nor category related queries were declared, so it was natural the user would received status 404.
I implemented those endpoints but I am still not very satisfied with some things:
- It seems like the (catalog api)[https://documenter.getpostman.com/view/845/catalogsystem-102/Hs44#daa0c5ee-5c69-a192-7228-29a395726e70] returns weird data, for example, categories query return a list of categories, and each of them has the url attribute, but when searching for an specific category via category query it returns an object without the url attribute. Who might be responsible for that API ? 
- Second, I imported the slugify lib via package.json but I'm having trouble using it. …
> add missing endpoints brand, category and categories

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Auth.graphql
- manifest.json
- node/graphql/index.ts
- node/resolvers/auth/index.ts
- node/resolvers/paths.ts
Create a new resolver to provide authentication through GraphQL mutations.
Makes possible to the frontend authenticate using GraphQL without the need to include the script of vtexID.
Access: https://login-resolver--storecomponents.myvtex.com/_v/graphiqlServer
```
mutation sendCode($email: String) {
vtex_storegraphql_2_0_2_sendEmailVerification(email: $email) {
vtex_storegraphql_2_0_2_authToken
}
}
#Perform the authentication passing the email, code and authToken (returned by the sendCode)
mutation signin($authInput: vtex_storegraphql_2_0_2_AuthInput) {
vtex_storegraphql_2_0_2_signIn(fields: $authInput) {
vtex_storegraphql_2_0_2_Name
vtex_storegraphql_2_0_2_Value
}
}
{
"email": "example@vtex.com",
"authInput": {
"email": "example@vtex.com",
"code": "886913",
"authToken": …
```
> Authentication resolver

- CHANGELOG.md
- node/resolvers/auth/index.ts
Set `HTTPOnly=true` on cookies, and remove the return of authToken to `signIn` mutation.
Its add the `HTTPOnly` on cookies. 
Access: https://bruno--storecomponents.myvtexdev.com/_v/graphiqlServer
Set the queries variables. Put your e-mail 
```
{
"email": "example@vtex.com.br",
"authInput": {
"email": "example@vtex.com.br",
"code": "217316",
"authToken": "427c90f0-2cb3-4aa8-9cd1-ad6034a104ea"
}
}
```
Execute this mutation and put the `authToken` in query variable object `authInput` Next, check your e-mail and put the access code too. 
```
mutation sendCode($email : String) { 
vtex_storegraphql_2_1_1_sendEmailVerification(email : $email) {
vtex_storegraphql_2_1_1_authToken
}
}
```
Execute this mutation and check in the headers response that `set-cookie` have HTTPOnly now. 
```
mutation …
```
> Fix authResolver to set HTTPOnly on cookies

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/resolvers/document/index.ts
- node/resolvers/paths.ts
Add  update document, on Master Data API
Provide a GraphQL layer to update generic documents.
Access: https://andre--storecomponents.myvtex.com/_v/vtex.store-graphql/graphiql/v1
```
mutation updateDocument($acronym: String, $documentToUpdate: vtex_storegraphql_2_1_1_DocumentInput) {
vtex_storegraphql_2_1_1_updateDocument(acronym: $acronym, document: $documentToUpdate) {
vtex_storegraphql_2_1_1_id
vtex_storegraphql_2_1_1_href
vtex_storegraphql_2_1_1_documentId
}
}
query getDocument($acronym: String, $id: String, $fieldsToQuery: [String]) {
vtex_storegraphql_2_1_1_document( acronym: $acronym, id: $id, fields: $fieldsToQuery) {
vtex_storegraphql_2_1_1_id
vtex_storegraphql_2_1_1_fields {
vtex_storegraphql_2_1_1_key
vtex_storegraphql_2_1_1_value
}
}
}
```
```
{
"acronym": "CL",
"id": …
```
> Update document through Master Data API

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/resolvers/catalog/index.ts
- node/resolvers/paths.ts
Give the possibility to the user to add a `map` param to the `Products` query and reject query terms that use invalid characters, as `? & = , [ ]`.
Access: https://andre--storecomponents.myvtex.com/_v/vtex.store-graphql/graphiql/v1
Query: 
```
query products($query:String,$orderBy:String, $map:String) {
products(query:$query, orderBy: $orderBy, map: $map) {
productName
}
}
```
Query variables:
```
{
"query": "TV",
"map": "c,c",
"orderBy": "OrderByNameASC"
}
```
> Fix products query to accept map param and reject invalid characters

- CHANGELOG.md
- graphql/types/Suggestions.graphql
- node/resolvers/catalog/index.ts
Add to the autocomplete query the `slug`  property
The `slug` property is needed by the search component to create the link to the product page.
Access: https://autocomplete-slug--storecomponents.myvtex.com/_v/vtex.store-graphql/graphiql/v1
```
query autocomplete {
autocomplete(searchTerm: "lg") {
itemsReturned {
name
href
slug
}
}
}
```
> Add to the autocomplete query the slug property

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- graphql/types/OrderForm.graphql
- manifest.json
- node/resolvers/checkout/index.ts
Change `orderForm ` query to parse prices to float
When the price component uses the query `OrderForm` the prices properties returns integer numbers instead float which is what this component expected.
Access: https://ordersform-resolver--storecomponents.myvtex.com/_v/vtex.store-graphql/graphiql/v1
**Query**: 
```
query orders {
orderForm {
orderFormId
value
items {
id
name
sellingPrice
price
}
}
}
```
> Change orderForm query to parse prices to float

- CHANGELOG.md
- manifest.json
- node/resolvers/profile/profileResolver.ts
It fixes permissions to get profile data form masterdata
There are some fields in masterdata that are `private`. It means you can't read them unless you have authorization. Our profile query is broken because it brings a lot of these `private` fields, like `email`.
```
"Forbidden access to the fields 'email'"
```
> Fix profile query

- .eslintrc
- .gitignore
- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Auth.graphql
- manifest.json
- node/package.json
- node/resolvers/auth/index.ts
- node/resolvers/catalog/index.ts
- node/resolvers/paths.ts
Now, this resolver authenticates only users of a context account
Before, the auth resolver were sign in admin mode.
To test [access here](https://dev--storecomponents.myvtex.com/_v/vtex.store-graphql/graphiql/v1?variables=%7B%0A%20%20%22email%22%3A%20%22example%40vtex.com%22%2C%0A%20%20%22authInput%22%3A%20%7B%0A%20%20%20%20%22email%22%3A%20%22example%40vtex.com%22%2C%0A%20%20%20%20%22code%22%3A%20%22791639%22%2C%0A%20%20%20%20%22authToken%22%3A%20%226CD4C196ED9DEFB727548AD991F4B61C446BC4468913D1DCDA360B93EF6F40B6%22%0A%20%20%7D%0A%7D&operationName=signin&query=mutation%20sendCode(%24email%3A%20String)%20%7B%0A%20%20sendEmailVerification(email%3A%20%24email)%20%7B%0A%20%20%20%20authToken%0A%20%20%7D%0A%7D%0A%0A%23Perform%20the%20authentication%20passing%20the%20email%2C%20code%20and%20auth …
> Fix authentication resolver to sign in only at users of a context account

- CHANGELOG.md
- node/resolvers/catalog/fieldsResolver.ts
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/recommendationsResolver.ts
Fix recommendations field resolver
The recommendation field was accessed by `fields.Product.recommendations` but the right path is `fields.recommendation`
[Access GraphiQL](v1?operationName=RelatedProducts&query=query%20RelatedProducts(%24slug%3A%20String)%20%7B%0A%20%20product(slug%3A%20%24slug)%20%7B%0A%20%20%20%20productName%0A%20%20%20%20categoryId%0A%20%20%20%20categories%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20kitItems%20%7B%0A%20%20%20%20%20%20%20%20product%20%7B%0A%20%20%20%20%20%20%20%20%20%20productName%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20recommendations%20%7B%0A%20%20%20%20%20%20view%20%7B%0A%20%20%20%20%20%20%20%20productName%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20buy%20%7B%0A%20%20%20%20%20%20%20%20productName%0A%20% …
> Fix recommendations field resolver

- CHANGELOG.md
- manifest.json
- node/resolvers/auth/index.ts
Set the maxAge received from VTEXID to VtexIdclientAutCookie_${account} cookie
Send expires date that was received by VTEXID API in the response. 
[Access here](https://login--storecomponents.myvtexdev.com/_v/vtex.store-graphql/graphiql/v1?query=mutation%20sendEmail%20%7B%0A%20%20sendEmailVerification(email%3A%22bruno.dias%40vtex.com%22)%0A%7D%0A%0Amutation%20signIn%20%7B%0A%20%20accessKeySignIn(fields%3A%7Bemail%3A%22bruno.dias%40vtex.com%22%2C%20code%3A%22496442%22%7D)%0A%7D%0A%0Amutation%20logout%7B%0A%20%20logout%0A%7D&operationName=logout)
> Set the maxAge received from VTEXID to VtexIdclientAutCookie_${account}

- CHANGELOG.md
- node/resolvers/profile/index.ts
- node/resolvers/profile/profileResolver.ts
- Fix profile resolver to use ioContext authToken.
- Profile Query will return the user email in case of data not found.
Profile resolver was using the client token to make requests to the Master Data.
Access: https://profile--storecomponents.myvtex.com/_v/vtex.store-graphql/graphiql/v1
**Data to make some tests:** 
> **_Needed to signIn first_**
> ````
>mutation sendCode {
>  sendEmailVerification(email:"email@vtex.com")
>}
>mutation signIn {
>  accessKeySignIn(fields:{
>    email:"email@vtex.com",
>    code:"CODE_SENT_TO_EMAIL"
>  })
>}
>````
```
mutation updateProfile {
updateProfile(fields: {
firstName: "Sherlock"
}) {
firstName,
lastName,
email
}
}
mutation createAddress {
createAddress(fields: {
street: "Beaker Str.",
number:"221b",
addressName: "Home"
}) {
address {
addressName
}
} …
```
> Fix profile resolver to use ioContext authToken

- CHANGELOG.md
- manifest.json
- node/resolvers/paths.ts
Add a condition to only use a category in the products' search query if there isn't a search term.  
When there's a category on the search URL the results only match this parameter, the search term is ignored.
> Fix products search query

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Auth.graphql
- manifest.json
- node/resolvers/auth/index.ts
- node/resolvers/checkout/index.ts
- node/resolvers/headers.ts
- node/resolvers/paths.ts
Add classic login in auth resolver
**Secondary** Refact the resolver to be more reusable.
You need to have a classic login in your account.
```
mutation classic{
classicSignIn(email:"bruno.dias@vtex.com", password:"")
}
```
>  Add classic login mutation

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/resolvers/auth/index.ts
- node/resolvers/paths.ts
Now, its possible create a password for an user. ✨ 
```
mutation sendEmail {
sendEmailVerification(email:"email@vtex.com")
}
mutation recoveryPassword{
recoveryPassword(email:"email@vtex.com", newPassword:"", code: "")
}
mutation classicSignIn{
classicSignIn(email:"email@vtex.com", password:"")
}
```
[Access here](https://login--storecomponents.myvtex.com/_v/vtex.store-graphql/graphiql/v1?operationName=recoveryPassword&query=mutation%20sendEmail%20%7B%0A%20%20sendEmailVerification(email%3A%22email%40vtex.com%22)%0A%7D%0A%0Amutation%20recoveryPassword%7B%0A%20%20recoveryPassword(email%3A%22email%40vtex.com%22%2C%20newPassword%3A%22%22%2C%20code%3A%20%22%22)%0A%7D%0A%23%20Test%20if%20your%20newPassword%20works!%0Amutation%20classicSignIn%7B%0A%20%20classicSignIn(email%3A%22email%40vtex.com%2 …
> Add recoveryPassword mutation in auth resolver

- CHANGELOG.md
- graphql/types/Brand.graphql
- graphql/types/Category.graphql
- graphql/types/Document.graphql
- graphql/types/OrderForm.graphql
- graphql/types/Product.graphql
- graphql/types/Profile.graphql
- graphql/types/Suggestions.graphql
- manifest.json
- node/package.json
- node/resolvers/catalog/fieldsResolver.ts
- node/resolvers/catalog/index.ts
- node/resolvers/checkout/index.ts
- node/resolvers/document/index.ts
- node/resolvers/profile/index.ts
- node/resolvers/profile/profileResolver.ts
- node/yarn.lock
The purpose is to add an ID to all cacheable root fields.
Client cannot cache data since they do not have an uniform cache ID.
Link -> Open GraphiQL -> try changed queries/mutations
> Added cacheId to return types of root fields

- CHANGELOG.md
- node/resolvers/benefits/index.ts
Fix breaking in Benefits Resolver.
The benefits resolver was breaking with the returned data being null.
<a href="https://gustavo--storecomponents.myvtex.com/_v/vtex.store-graphql/graphiql/v1">Workspace</a>
```gql
query Product($slug: String) {
product(slug: $slug) {
benefits {
name
}
}
}
```
```json
{
"slug": "motorola-moto-x4"
}
```
> Benefits Resolver Breaking

- CHANGELOG.md
- graphql/types/Facets.graphql
- Add PriceRanges to facets graphql type
[graphiql query example](https://pricerange--storecomponents.myvtex.com/_v/vtex.store-graphql/graphiql/v1?query=query%20facets%20%7B%0A%20%20facets(facets%3A%20%22eletronics%3Fmap%3Dc%22)%20%7B%0A%20%20%20%20PriceRanges%20%7B%0A%20%20%20%20%20%20Quantity%0A%20%20%20%20%20%20Name%0A%20%20%20%20%20%20Link%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=facets)
[graphiql link](https://pricerange--storecomponents.myvtex.com)
```
query facets {
facets(facets: "eletronics?map=c") {
PriceRanges {
Quantity
Name
Link
}
}
}
```
> Add PriceRanges to facets graphql type

- CHANGELOG.md
- node/resolvers/benefits/index.ts
Resolve null fields of product data in benefits resolver.
Attributes like `clusterHighlights` and others were come with null values and stay without treatment.
<a href="https://gustavo--storecomponents.myvtex.com/_v/vtex.store-graphql@2.10.0/graphiql/v1">Workspace</a>
```gql
query Query($slug: String) {
product (slug: $slug) {
clusterHighlights {
id
name
}
}
}
```
```json
{
"slug": "porsche-911"
}
```
> Add local fields resolver to benefits resolver

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Profile.graphql
- manifest.json
- node/resolvers/paths.ts
- node/resolvers/profile/index.ts
- node/resolvers/profile/profileResolver.ts
Adds extensible profile info to schema graphql and implementation
Today, devs can not use their own fields in CL entities in masterdata. This PR solves this problem
1. Link this PR, open graphiql
2. login with login mutations
3. make the updateProfile mutation with custom fields to profile entity
4. retrieve than with profile query
> Adding extensible profile info so apps can use CL entity correctly

- CHANGELOG.md
- manifest.json
- node/resolvers/profile/index.ts
This pull request fixes a problem where the `updateProfile` mutation would crash if no custom fields were provided as argument.
> Add default value for custom fields on updateProfile

- CHANGELOG.md
- manifest.json
- node/resolvers/profile/profileResolver.ts
Modifying the profile data only when isn't undefined.
Custom fields error when profile data is null
> Fix custom fields error when profile data is null

- CHANGELOG.md
- manifest.json
- node/resolvers/profile/index.ts
When a `mutation profileUpdate` is made with customFields only, an `undefined` error is thrown. This pr solves this issue
> Fix profileUpdate for customFields only

- CHANGELOG.md
- manifest.json
- node/resolvers/paths.ts
Change the API used in the catalog for search in Gocommerce when it's a Gocommerce account or in VTEX catalog when not.
The systems has different API for catalog, so the resolver needs to search in the right one.
> Search in Gocommerce catalog when account is Gocommerce

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/fieldsResolver.ts
Now, all images of the product will return with `https.`
Fix this issue ![screen shot 2018-08-08 at 18 31 43](https://user-images.githubusercontent.com/8000984/43865573-58e7cc52-9b39-11e8-83d5-63dd8d63761d.png)
[query](https://graphql--storecomponents.myvtex.com/_v/vtex.store-graphql@2.17.0/graphiql/v1?query=query%20product%20%7B%20%0A%09product%20(slug%3A%20%22tenis-mizuno-wave-viper-3-masculino%22)%20%7B%0A%20%20%20%20productId%0A%20%20%20%20productName%0A%20%20%20%20items%7B%0A%20%20%20%20%20%20images%7B%0A%20%20%20%20%20%20%20%20imageId%0A%20%20%20%20%20%20%20%20imageUrl%0A%20%20%20%20%20%20%20%20imageText%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=product)
> Replace http to https in item imageUrl

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Document.graphql
- manifest.json
- node/resolvers/document/attachment.ts
- node/resolvers/document/index.ts
- node/resolvers/paths.ts
- node/resolvers/profile/index.ts
This adds masterdata's attachment API and uses it for uploading profile picture. Also, this PR adds to modes to upload profile picture:
- UploadProfilePicture: appends profile picture to previous ones
- UpdateProfilePicture: replaces previous profile pictures with new one
> Adds Masterdata's attachment upload API

- CHANGELOG.md
- graphql/types/OrderForm.graphql
- manifest.json
- node/resolvers/checkout/index.ts
Add enableCookies on checkout mutations
[access here](https://graphql--storecomponents.myvtex.com/_v/vtex.store-graphql@2.19.1/graphiql/v1?operationName=getOrderForm&query=mutation%20profileOrderForm%20(%24fields%3A%20OrderFormProfileInput)%7B%0A%20%20updateOrderFormProfile(orderFormId%3A%20%22%22%2C%20fields%3A%20%24fields%20)%20%7B%0A%20%20%20%20orderFormId%0A%20%20%7D%0A%7D%0A%0Aquery%20getOrderForm%7B%0A%20%20orderForm%20%7B%0A%20%20%20%20orderFormId%0A%20%20%20%20clientProfileData%20%7B%0A%20%20%20%20%20%20email%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22fields%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22email%22%3A%20%22bruno.dias%40vtex.com.br%22%2C%20%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Bruno%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Dias%2 …
> Add enableCookies on checkout mutations

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/index.ts
Changes the response of the search query to filter the facets based on the query made.
There were some inconsistencies in the facets returned in the query, because the values returned didn't include the parameters passed on the `rest` argument.
[Access this workspace](https://specificationfilter--storecomponents.myvtex.com/eletronicos/smartphones?map=c%2Cc).
> Filter facets in search response

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Session.graphql
- manifest.json
- node/graphql/index.ts
- node/resolvers/catalog/index.ts
- node/resolvers/checkout/paymentTokenResolver.ts
- node/resolvers/httpResolver.ts
- node/resolvers/paths.ts
- node/resolvers/profile/index.ts
- node/resolvers/session/index.ts
- node/resolvers/session/sessionResolver.ts
Add `initializeSession`, `impersonate`, `depersonify` mutations to telemarketing app.
Change the fetch that `vtex.telemarketing` is doing to mutations.
Set your user at admin of `storecomponents` account with the profile access **Televendas** them execute the mutations in this order: `initializeSession`, `impersonate`, `depersonify`. 
[test here](https://session--storecomponents.myvtex.com/_v/vtex.store-graphql@2.20.2/graphiql/v1?operationName=despersonify&query=mutation%20initSession%20%7B%0A%20%20initializeSession%20%7B%0A%20%20%20%20cartId%0A%20%20%20%20impersonate%0A%20%20%20%20id%0A%20%20%20%20adminUserId%0A%20%20%20%20adminUserEmail%0A%20%20%20%20profile%20%7B%0A%20%20%20%20%20%20isAuthenticatedAsCustomer%0A%20%20%20%20%20%20lastName%0A%20%20%20%20%20%20firstName%0A%20%20%20%20%7D%0A …
> Add initializeSession, impersonate, depersonify mutations to telemarketing app.

- CHANGELOG.md
- graphql/types/Benefits.graphql
- manifest.json
- node/resolvers/benefits/index.ts
- node/resolvers/catalog/index.ts
- node/resolvers/paths.ts
Ensure that the `Benefits Resolver` will only use public endpoints to retrieve the data that is needed.
The Benefits Resolver was using private endpoints to retrieve the data thas is needed. In the case that the user is not logged the data provided by the resolver will not be retrieved.
<a href="https://public-benefits--storecomponents.myvtex.com/_v/vtex.store-graphql@2.20.2/graphiql/v1" target="_blank">Workspace</a>
```gql
query Benefit($items: [ShippingItem]) {
benefits(items: $items) {
id
featured
name
items {
benefitProduct {
productId
productName
items {
itemId
name
}
}
discount
minQuantity
}
teaserType
}
}
```
```json
{
"items": [
{
"id": "1",
"quantity": "1",
"seller": "1"
}
]
}
```
> `Benefits Resolver` using only public endpoints.

- CHANGELOG.md
- graphql/types/Facets.graphql
- manifest.json
Include the new optional fields `Slug` and `Id` to the facets type.
On some fields, you needed to rely on parsing the `Link` string to retrieve the appropriate slug. Now, you can get the value directly from the `Slug` (in the case of the price ranges) or the `Id` (in the case of the categories).
> Update facets fields to include slug and id

- CHANGELOG.md
- graphql/types/Benefits.graphql
- node/resolvers/benefits/index.ts
When a benefit is created it is created based on the SKU's which composes the benefits itself.
The data provided by the Benefit Resolver now contains a list of the SKU IDs that composes the Benefit. 
The data provided by the Benefit Resolver has no information about what SKU must be in the benefit.
Workspace: https://gugabribeiro--storecomponents.myvtex.com/_v/vtex.store-graphql@2.25.0/graphiql/v1
```gql
query Product($slug: String) {
product(slug: $slug) {
benefits {
items {
benefitProduct {
productName
productId
items {
name
itemId
}
}
benefitSKUIds
}
}
}
}
```
```json
{
"slug": "porsche-911"
}
```
> SKU Items of the Benefit

- CHANGELOG.md
- manifest.json
- node/resolvers/auth/index.ts
- node/resolvers/paths.ts
*Secondary: Refact the auth mutations to make `POST` instead `GET` requests in API.*
Use login app -> https://auth--storecomponents.myvtex.com/
> Fix /start path of VTEX ID API

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Session.graphql
- manifest.json
- node/graphql/index.ts
- node/resolvers/session/index.ts
- node/resolvers/session/sessionResolver.ts
Sign in as a user in store (use login app). 
And [access here](https://login--storecomponents.myvtex.com/_v/vtex.store-graphql@2.23.2/graphiql/v1?query=query%20session%20%7B%0A%20%20getSession%20%7B%0A%20%20%20%20profile%20%7B%0A%20%20%20%20%20%20firstName%0A%20%20%20%20%20%20lastName%0A%20%20%20%20%20%20email%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0Amutation%20impersonate%20%7B%0A%20%20impersonate%20(email%3A%22contato%40diasbruno.com%22%2C%20orderFormId%3A%22d0c6f4ed760343adbac7e87999ba5400%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20adminUserId%0A%20%20%20%20impersonable%0A%20%20%20%20impersonate%20%7B%0A%20%20%20%20%20%20storeUserId%0A%20%20%20%20%20%20storeUserEmail%0A%20%20%20%20%7D%0A%20%20%20%20profile%20%7B%0A%20%20%20%20%20%20firstName%0A%20%20%20%20%20%20lastName%0A%20%20%20%20%20%20e …
> Add session query and remove initializeSession mutation

- CHANGELOG.md
- node/resolvers/catalog/index.ts
There is a type mismatch between the function and the argument making the final url to be something like`/api/catalog_system/pub/tree/[Object]/`
Link boticario store with an older version to notice the bug in the store-graphql logs
> should not pass an object

- CHANGELOG.md
- manifest.json
- node/resolvers/profile/index.ts
The `updateProfile` mutation don't update profileData when was a new user.
> Fix updateProfile mutation to update information of new users

- CHANGELOG.md
- graphql/types/OrderForm.graphql
- manifest.json
- node/resolvers/checkout/index.ts
Enable querying of shippingData on the orderForm object, and fixes the resolver of the updateOrderFormShipping mutation
For the app `address-locator` and `delivery-dreamstore`, we need to be able to read and update the shippingData, with the purpose of changing the delivery address.
Use graphiQL to query shippingData on the orderForm query, and use the updateOrderFormShipping mutation to change the address. Sample address variable (replace `{{orderFormId}}` with the id from a previous query):
```json
{ "orderFormId": "{{orderFormId}}", "address": { "street": "Praia de Botafogo", "number":"300", "postalCode": "22250-040" } }
```
Workspace: https://updateorderformshipping--delivery.myvtex.com/_v/vtex.store-graphql@2.31.1/graphiql/v1
> Feature: shippingData query and address mutation

- CHANGELOG.md
- graphql/types/Logistics.graphql
- manifest.json
Be able to query googleMapsKey from the logistics API
Use the workspace link below and execute the query, it should return the same key from Google Maps that is configured in Logistics at https://delivery.myvtex.com/admin/logistics/#/config
Workspace: https://prgooglemaps--delivery.myvtex.com/_v/vtex.store-graphql@2.31.5/graphiql/v1?query=query%20logistics%20%7B%0A%20%20logistics%20%7B%0A%20%20%20%20googleMapsKey%0A%20%20%7D%0A%7D&operationName=logistics
> Enable querying of googleMapsKey on LogisticsData type

- CHANGELOG.md
- manifest.json
- node/dataSources/checkout.ts
- node/resolvers/checkout/index.ts
Resolve a quirk in updateOrderFormShipping. I double checked if there is any code using this already, and no, so it should not be a breaking change, more like fixing what's broken
The method `updateOrderFormShipping` in `node/dataSources/checkout.ts` is spreading the shipping object into the POST request. I had to get the address object that is being received and passed it to the datasource inside another object, that way when someone needs to add a feature to it, they just need to append it there. I renamed the dataSource object to make more sense (it was called address before, but it could have other objects like logisticsInfo, not just addres).
- Access the graphiQL url below
- Execute the orderForm query
- Get the orderFormId from the query result, and paste it into the query …
> Fix usage of updateOrderFormShipping

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/index.ts
Add vary x-vtex-segment to prevent wrong cached responses
We can deliver wrong cached responses that should vary by vtex_segment cookie
> Add vary x-vtex-segment to prevent wrong cached responses

- CHANGELOG.md
- manifest.json
- node/resolvers/index.ts
> Long stack traces imply a substantial performance penalty, around 4-5x for throughput and 0.5x for latency.
http://bluebirdjs.com/docs/api/promise.longstacktraces.html
> Disable long stack traces

- CHANGELOG.md
- manifest.json
- node/dataSources/catalog.ts
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/search.ts
Isolate the query to the `facets` and `products` api from the `search` query, so it will only make the request to the catalog if the user query has the respective `facets` and `products`.
This will make possible to query the `search` with an empty query and map parameter, without breaking the query, due to a limitation in the facets api that can't be queried without those arguments.
[Workspace](https://lucas--storecomponents.myvtex.com/eletronicos/d)
> Isolate products and facets queries on search

- CHANGELOG.md
- manifest.json
- node/service.json
I've seen the average CPU usage of this app is
around 2.5 only for Boticario. This means that
we'd need 5 replicas to keep a healthy 0.5 cpu usage
per instance.
Set minReplicas to 6 to leave a little gordurinha.
> Increase minReplicas to 6

- CHANGELOG.md
- graphql/types/OrderForm.graphql
Make possible add items on cart from other sellers rather than principal
Cast problem trying to convert a string to a Int on OrderFormInput
Try add an item on cart that belongs to other seller
> Fix seller field type on OrderFormInput

- CHANGELOG.md
- manifest.json
- node/dataSources/portal.ts
- node/package.json
- node/routes/catalogProxy.ts
- node/yarn.lock
The resolution if the current account is GoCommerce is replicated in many projects of the VTEX infrastructure, for that reason a function was created at `@gocommerce/util` module to centralise the code in one place
Replicated code in VTEX projects
link this project at a VTEX or GoCommerce store
> add isGoCommerceAcc function from @gocommerce/utils

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
This PR depends on these ones:
- [builder-hub](https://github.com/vtex/builder-hub/pull/306)
- [graphql-server](https://github.com/vtex/graphql-server/pull/136)
- [render-ssr](https://github.com/vtex/render-ssr/pull/17)
- [pages-graphql](https://github.com/vtex/pages-graphql/pull/99)
- [runtime-node](https://github.com/vtex/service-runtime-node/pull/92)
The main idea behind all of these PRs is that we need to have access to the segment cookie on SSR and on virtual public resolvers. To address this problem without jeopardizing our public cache, a new route was designed, the `/_v/segment`. To use this route, a new `SEGMENT` scope was added to our graphql spec. This scope has a side effect of varying the response with the segment header.
> Using new segment scope

- CHANGELOG.md
- manifest.json
- node/dataSources/document.ts
They way apollo datasource is implemented makes that we cannot override it's headers. This PR fixes a bug caused by overriding it's header object by using the `set` method
> should not overwrite headers object from apollo datasource

- CHANGELOG.md
- graphql/types/ItemMetadata.graphql
- graphql/types/Order.graphql
- graphql/types/OrderForm.graphql
- graphql/types/Product.graphql
- manifest.json
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/itemMetadataUnit.ts
wks para teste: https://storeteste--delivery.myvtex.com
Adicionar os campos de assembly options nos tipos de OrderForm, Order e Product
Esses campos serão úteis quando algum dia podermos mergear as alterações de assembly options em master (quando saírem do beta).
Isso ajuda pois diminui a PR de assembly options. Não afeta em nada o que já existe.
Acessar https://storeteste--delivery.myvtex.com e adicionar algo simples ao carrinho.
> add assembly options related fields to orderform and product types

- CHANGELOG.md
- manifest.json
- node/directives/withCurrentProfile.ts
- node/resolvers/profile/fieldResolvers.ts
- node/resolvers/profile/services.ts
#198 introduced a bug with the following error:
`Invalid token specified`
This pr fixes this error by correctly parsing the admin jwt token and returning null when necessary in `withCurrentProfile` directive resolver
> Fixing Invalid token specified in profile query

- CHANGELOG.md
- manifest.json
- node/dataSources/payments.ts
- node/package.json
- node/tsconfig.json
- node/typings.d.ts
- node/yarn.lock
We were having lots of errors like this one in `PaymentsDataSource`: 
```
invalid json response body
reason: Unexpected end of JSON input
```
This error happens because `profile-system` responds a 200 status code for an empty body with the header `Content-Type: application/json` set. ApolloDataSourceREST uses `node-fetch` behind the scenes. When `node-fetch` receives a `Content-Type: application/json` with a 200 status code, it blindly tries to `JSON.parse` the body, causing the error.
To fix this issue and also align to our vision of using only one DataSources library, I created this PR that uses IODataSoure instead of the Apollo DatasSourceREST. Since IODataSoure uses `axios` for the http client, the main issue is gone for now.
However, when I was developing this PR, I found this …
> Using IODataSource instead of buggy Apollo DatasSourceREST

- CHANGELOG.md
- graphql/types/List.graphql
- manifest.json
- node/dataSources/document.ts
- node/resolvers/list/index.ts
The requests made from Document DataSources was crashing because the MasterData was expecting a Header Object instead of a JSON one.
[Click here to access the GraphiQL.](https://waza2--storecomponents.myvtex.com/_v/vtex.store-graphql@2.45.0/graphiql/v1)
> Fix headers' error in Document DataSource

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Order.graphql
- manifest.json
- node/dataSources/catalog.ts
- node/dataSources/checkout.ts
- node/dataSources/oms.ts
- node/directives/index.ts
- node/directives/withSegment.ts
- node/resolvers/oms/index.ts
This PR adds the withSegment directive resolver that opens the incoming segment request. With the segment oppened, we can use the sales channel while querying checkout and catalog APIs
> Note: This was an "extreme go horse" feature and requires further testing
> Sales channel checkout calatalog

- CHANGELOG.md
- manifest.json
- node/resolvers/document/index.ts
This PR proposes a fix to the `updateDocument` resolver which seems to be passing wrong arguments to `Document.updateDocument`.
> Fix Document.updateDocument call in updateDocument resolver

- CHANGELOG.md
- manifest.json
- node/resolvers/document/index.ts
Refactors `id` parsing in the `updateDocument` resolver by using the `parseFieldsToJson` function.
> Refactor id parsing in updateDocument resolver

- CHANGELOG.md
- manifest.json
- node/resolvers/auth/index.ts
Title is self-explanatory.
The call to makeRequest function was missing an argument to define the method of the HTTP request. Thus, an 404 error was thrown every time this resolver was called.
Make a call to redefinePassword mutation and check if the result is a success. Then, test if the password has, in fact, changed to the set value.
> Fix makeRequest function call

- CHANGELOG.md
- manifest.json
- node/resolvers/checkout/sessionManager.ts
Fixes the issue given by this query 
[index=colossus sender=vtex.store-graphql@*  "body.details.0.message"="argument str must be a string"| spath region | search region="aws-us-east-1"](https://splunk7.vtex.com/en-US/app/vtex_colossus/search?q=search%20index%3Dcolossus%20sender%3Dvtex.store-graphql%40*%20%20%22body.details.0.message%22%3D%22argument%20str%20must%20be%20a%20string%22%7C%20spath%20region%20%7C%20search%20region%3D%22aws-us-east-1%22&earliest=-60m%40m&latest=now&display.page.search.mode=fast&dispatch.sample_ratio=1&display.general.type=events&display.page.search.tab=events&sid=1552509292.25706_B07AC1AB-7164-44F1-8003-70F0A649A707)
When there is no cookies being used, the method `parse` of `cookie` library fails with code 
```
argument str must be a string
```
The fix drops …
> fix parsing empty cookie

- CHANGELOG.md
- manifest.json
- node/resolvers/profile/services.ts
Fixes the issue given by this query
[index=colossus sender=vtex.store-graphql@2.57.3  "body.details.0.message"="Cannot read property 'reduce' of null"](https://splunk7.vtex.com/en-US/app/vtex_colossus/search?q=search%20index%3Dcolossus%20sender%3Dvtex.store-graphql%402.57.3%20%20%22body.details.0.message%22%3D%22Cannot%20read%20property%20%27reduce%27%20of%20null%22&earliest=-60m%40m&latest=now&display.page.search.mode=fast&dispatch.sample_ratio=1&sid=1552515642.31150_758F1174-7E15-4996-8733-56204ADE7565)
When there are no extra fields the reduce fails with `Cannot read property 'reduce' of null`. This issue was fixed by checking the nullity of extraFields variable
> Check if extrafields is defined

- CHANGELOG.md
- manifest.json
- node/package.json
- node/resolvers/auth/index.ts
- node/resolvers/paths.ts
Requests to vtexid should be made by using a `'content-type': 'application/x-www-form-urlencoded'` POST request and using HTTPS.
I could not test the password change, so I did not applied the fix, however it should be simple. 
The only resolvers fixed are ` accessKeySignIn` and `classicSignIn `
Login is made by passing the password and email directly in the querystring
> Fix plain text credentials in login and use HTTPS

- CHANGELOG.md
- manifest.json
- node/resolvers/checkout/index.ts
On `addItem` mutation, return a new order form with cart updated after adding assembly options.
Necessary for link state feature.
> return new order form if adding options on addItem

- CHANGELOG.md
- lint.sh
- manifest.json
- node/dataSources/catalog.ts
- node/dataSources/messages.ts
- node/dataSources/payments.ts
- node/dataSources/profile.ts
- node/index.ts
- node/package.json
- node/resolvers/catalog/index.ts
- node/routes/catalogProxy.ts
- node/typings.d.ts
- node/yarn.lock
Caching and adding decent metrics (separated by env) to all catalog access.
> É verdade esse bilete
> Update to new node-vtex-api with metrics and add 2000-keys memory cache for catalog proxy

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/dataSources/profile.ts
- node/resolvers/catalog/product.ts
- node/resolvers/profile/index.ts
- node/typings.d.ts
Make it possible to add a new component to add an email to a newsletter.
Add a new mutation so anyone can add an email to receive newsletter.
https://breno--storecomponents.myvtex.com/_v/vtex.store-graphql@2.57.1/graphiql/v1?query=mutation%20sub%20%7B%0A%20%20subscribeNewsletter(email%3A%20%22uahseusahe%40masease.com%22)%0A%7D&operationName=sub
And check the value stored in MasterData:
https://storecomponents.vtexcrm.com.br/#RHluYW1pY0Zvcm0jRm9ybVZpZXcjcm93SWQ9Q0wtZjJmNjc3NTQtNDVkOS0xMWU5LTgyNjUtZGU0MDNhZjZhNTY3JmZvcm1JZD1lYTAyMjY1Zi03ZmE1LTQ4MWMtYmU3My1kOThjNmFlNGE5ZWQmd29ya2Zsb3dJZD0jRHluYW1pY0Zvcm1fQmVnaW4jRm9ybVZpZXdfQ29tcGxldGUoJ0NMLWYyZjY3NzU0LTQ1ZDktMTFlOS04MjY1LWRlNDAzYWY2YTU2NycpOyBEeW5hbWljRm9ybV9Gb3JtVmlld19BZnRlckxvYWQoKTsjbnVsbCNBamF4UmVxdWVzdEVycm9yI3RlbXBEaXY=
```graphql …
```
> Add new mutation subscribeNewsletter

- CHANGELOG.md
- manifest.json
- node/directives/withCurrentProfile.ts
- node/globals.ts
- as the title says...
- The user logs in for the first time, with no purchase history, the vtex-id creates a user so he can sign in but it doesn't create a profile for that user, so he has the userId but not the profile.
- Log in with a user, go to the my-account and try to upload a new profile-picture.
[linked workspace](https://fixprofile--recorrenciaqa.myvtexdev.com/account)
> Create a profile for the user if he is logged but hasn't one yet

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/itemMetadata.ts
You can test it [here](https://maceio--phmex.myvtex.com/_v/vtex.store-graphql@2.64.2/graphiql/v1?query=query%20promo%20%7B%0A%20%20product(slug%3A%22promo-952%22)%7B%0A%20%20%20%20itemMetadata%7B%0A%20%20%20%20%20%20priceTable%7B%0A%20%20%20%20%20%20%20%09type%20%0A%20%20%20%20%20%20%20%20values%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20price%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=promo)
Before this, the node `itemMetadata` would return null if any subitem price consulting came up wrong. I've added another check that solves the main problem.
_(For some reason, after I've extracted the check,  `eslint` would not recognise my `orderForm` guard, so I've had to add an `as any` there)_
I've skipped …
> Fixes priceTable fetching

- CHANGELOG.md
- graphql/types/Facets.graphql
- manifest.json
Remove required on `Slug` field in the `Facet` type.
The `slug` field isn't required, so as the `Slug` should be, and this was causing errors in some accounts.
> Remove required in slug field

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/ProductSearch.graphql
- manifest.json
- node/resolvers/catalog/index.ts
Add the product search query.
With this query, you can get the `recordsFiltered` property that's returned from the API as the `resources` header.
[GraphiQL](https://lucas--storecomponents.myvtex.com/_v/vtex.store-graphql@2.69.1/graphiql/v1).
> Add product search query

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/category.ts
Fix flattening of categories and  add `/d` to `href` when it's department.
Linking to a category or department.
https://breno--storecomponents.myvtex.com/_v/vtex.store-graphql@2.70.1/graphiql/v1?query=query%20%7B%0A%20%20department%3A%20category(id%3A%2016)%20%7B%0A%20%20%20%20href%0A%20%20%20%20slug%0A%20%20%20%20name%0A%20%20%7D%0A%20%20category%3A%20category(id%3A%203)%20%7B%0A%20%20%20%20href%0A%20%20%20%20slug%0A%20%20%20%20name%0A%20%20%7D%0A%20%20subcategory%3A%20category(id%3A%2013)%20%7B%0A%20%20%20%20href%0A%20%20%20%20slug%0A%20%20%20%20name%0A%20%20%7D%0A%7D%0A
>  Add '/d' on department 'href'

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/facets.ts
Update the `selected` property computation to account for the `map` in the facet value, when comparing against the query inputs.
In Invicta, we have a category with the same name as the brand, which was causing the brand to appear as a selected facet, although only the category was selected.
[workspace](https://lucas--storecomponents.myvtex.com/clothing/Bord%C3%B4?map=c%2CspecificationFilter_38).
> Fix selected property not accounting for map field

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/index.ts
As the title says
[Test here](https://meta--storecomponents.myvtex.com/_v/vtex.store-graphql@2.71.2/graphiql/v1?operationName=search)
```
query search {
productSearch(query: "Clothing", map: "c") {
titleTag
metaTagDescription
}
}
```
> Add Category/Brand name in titleTag when meta tag title are null

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/facets.ts
Remove the slugify call on the facets value when checking if the facet was selected or not.
The values are already slugified from the API, and this second "slugification" was breaking some values, marking some as not selected when, in fact, they were.
[workspace](https://lucas--invictastores.myvtex.com/watches/Mens/Technomarine/S--Coifman?map=c%2CspecificationFilter_69%2Cb%2Cc), select the "watches" and the "S Coifman" filter should be gone.
> Remove slugify on facets

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/index.ts
Remove comma from invalid query term regex.
If you have a filter that has a comma in the product specification, it breaks the search when you apply that filter.
[workspace](https://lucas--invictastores.myvtex.com/watches/Technomarine/Technomarine?map=c%2Cb%2Cc), select a case tone with a comma in it.
> Fix comma in product query breaking search

- CHANGELOG.md
- manifest.json
- node/dataSources/catalog.ts
- node/resolvers/catalog/autocomplete.ts
- node/resolvers/catalog/index.ts
- node/utils/ioMessage.ts
Uses messages in autocomplete and productSearch resolvers for translating terms before sending then to catalog API
To test, just visit this [link](https://gimenes--storecomponents.myvtex.com/)
> translates query terms for productSearch and autocomplete

- CHANGELOG.md
- manifest.json
- node/resolvers/profile/fieldResolvers.ts
- node/resolvers/profile/services.ts
Title is self-explanatory
If it was an impersonated user, an error would be thrown, not allowing him/her to access personal data.
https://arthur--recorrenciaqa.myvtexdev.com/_v/vtex.store-graphql@2.73.3/graphiql/v1
> Add check for when user is impersonated in passwordLastUpdate

- CHANGELOG.md
- graphql/types/ProductSearch.graphql
- manifest.json
- node/dataSources/catalog.ts
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/productSearch.ts
- node/resolvers/catalog/searchBreadcrumb.ts
- node/resolvers/catalog/slug.ts
- node/resolvers/catalog/utils.ts
- node/typings/Catalog.ts
- node/utils/ioMessage.ts
https://fidelis--invictastores.myvtex.com/_v/vtex.store-graphql@2.74.3/graphiql/v1
Please try queries like:
https://fidelis--invictastores.myvtex.com/_v/vtex.store-graphql@2.74.3/graphiql/v1?query=query%20%7B%0A%20%20brand%3A%20productSearch(query%3A%20%22collections%2FMens%2FS--Coifman%22%2C%20map%3A%20%22c%2CspecificationFilter_69%2Cb%22)%20%7B%0A%20%20%20%20breadcrumb%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20href%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20cluster%3A%20productSearch(query%3A%20%22collections%2F140%22%2C%20map%3A%20%22c%2Cc%22)%20%7B%0A%20%20%20%20breadcrumb%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20href%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
With categories, specification filters, brand:
```
query {
productSearch(query: "collections/Mens/S--Coifman", map: …
```
> implement breadcrumb field on product search

- CHANGELOG.md
- manifest.json
- node/dataSources/catalog.ts
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/productSearch.ts
Every search we would do the same query twice at the catalog, one for the products and other just to get the response header and get the records filtered.
This PR makes both resolver get the data from the same query.
https://prodsearch--invictastores.myvtex.com/_v/vtex.store-graphql@2.76.0/graphiql/v1?query=query%20%7B%0A%20%20productSearch%20(query%3A%20%22collections%22%2C%20map%3A%22c%22)%20%7B%0A%20%20%20%20products%20%7B%0A%20%20%20%20%20%20productName%0A%20%20%20%20%7D%0A%20%20%20%20recordsFiltered%0A%20%20%20%20breadcrumb%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20href%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
> get recordsFiltered and products from same catalog query

- graphql/schema.graphql
- node/clients/masterdata.ts
- node/globals.ts
- node/resolvers/document/index.ts
To add schema parameter to docs search query
There has to be a query schema parameter in order for users to choose the correct schema for their Master Data entities
Query documents using a schema parameter and choose the schema to make the request
> [ENHANCEMENT] Added schema parameter do documents query

- node/clients/masterdata.ts
To fix an extra comma on the dataentities query parameters url
Dataentities request had an extra comma at the end of the fields query url, which produced an `Cannot read private fields` error.
Create a query on Graphiql and see the url request path produced. At the _fields query param, you should see no extra comma before the _where param.
> [BUGFIX] Removed comma from query url on dataentities request

- CHANGELOG.md
- manifest.json
- policies.json
The legacy format will no longer be supported soon.
> Fix policies in legacy format

- CHANGELOG.md
- node/clients/catalog.ts
Allow product graphQL queries to work correctly when using EAN and Reference identifiers.
`productByEan` and `productByReference` were incorrectly using a "=" character instead of a ":" when sending a request to the catalog API.
Checkout this branch, link to a workspace, then use GraphiQL to query a product using EAN or Reference Code. For example this query on account alssports:
```
query product {
product(identifier: { field: reference, value: "PAT24020"}) {
productName
}
}
```
> Corrected query string formats for catalog client methods

- node/package.json
- node/resolvers/auth/index.ts
- node/resolvers/catalog/index.ts
- node/resolvers/httpResolver.ts
- node/yarn.lock
- Add support to categories, departments and subcategories whose URLs contain special characters;
- Upgrade `axios`, since a vulnerability issue has been discovered in the current version.
The following issue: https://github.com/vtex-apps/admin-pages/issues/190.
> It looks like conditions doesn't work under a coded page url, the options can't be changed and I am "forced" to set up the configuration to the template.
Reproducing the bug (taken from the aforementioned issue):
1. Open the `vtexdebug` workspace from the `newbalance` account ([link](https://vtexdebug--newbalance.myvtex.com/admin/cms/storefront)).
2. > Navigate to subcategory "Bonés" within Female department and try to set up the "Category Text" block. I've noticed that now we have a toast message saying that it could't find a …
> Fix: search context criteria

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/catalog.ts
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/utils.ts
Added productsByIdentifier query and associated resolver to retrieve multiple products from an array of identifiers (EAN, reference code, etc)
I'm working on a Wordpress app that includes a feature to show a shelf of products related to a particular article. The customer tags the blog post with one or more product reference codes. This commit allows products to be queried with an array of reference codes or other identifiers.
Go to: https://graphql--alssports.myvtex.com/admin/graphql-ide
Select the linked `vtex.store-graphql` from the dropdown
Perform this query:
```
query products {
productsByIdentifier(field: reference, values: ["PAT24020", "simms-boot_freestone_felt"]) {
productName
}
}
```
> Added productsByIdentifier query

- CHANGELOG.md
- graphql/types/Shipping.graphql
Exito needs to get the deliveryIds in the Query for Shipping simulation to know if the product can be delivered in pick up points.
[The query can be tested here in graphiql](https://vtexexito--prueba1.myvtex.com/_v/vtex.store-graphql@2.81.0/graphiql/v1?query=query%20getShippingEstimates(%24items%3A%20%5BShippingItem%5D%2C%20%24postalCode%3A%20String%2C%20%24country%3A%20String)%20%7B%0A%20%20shipping(items%3A%20%24items%2C%20postalCode%3A%20%24postalCode%2C%20country%3A%20%24country)%20%7B%0A%20%20%20%20logisticsInfo%20%7B%0A%20%20%20%20%20%20itemIndex%0A%20%20%20%20%20%20slas%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20price%0A%20%20%20%20%20%20%20%20shippingEstimate%0A%20%20%20%20%20%20%20%20shippingEstimateDate%0A%20%20%20%20%20%20%20%20de …
> Adding deliveryIds fields in ShippingSimulation Query

- CHANGELOG.md
- graphql/types/OrderForm.graphql
- manifest.json
- node/globals.ts
- node/resolvers/checkout/orderFormItem.ts
Added ProductCategoryIds in each item of an OrderFormItem
Allows the category id in the items
we can add productCategoryIds section to item in OrderForm graphql query and run that query in graphql console
> Added product category ids on OrderFormItem

- CHANGELOG.md
- graphql/types/Order.graphql
Adding support for `productCategoryIds` in `OrderItem` type.
Currently there's no way to tell if the items of an order match a certain category.
With the `productCategoryIds` we can validate and show specific options related to that item.
1. Go to the [GraphiQL](https://form--tokstok.myvtex.com/_v/vtex.store-graphql@2.80.3/graphiql/v1?query=query%20orders%20%7B%0A%20%20orders%20%7B%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20productCategoryIds%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=orders);
2. Login to https://form--tokstok.myvtex.com/login
3. Execute the Query.
> Add support for productCategoryIds in OrderItem type

- CHANGELOG.md
- graphql/types/Order.graphql
Some Apps have to verify if `invoicedDate` is between some date to validate the order to continue the flow like a "Returning Products" or similar.
With the `invoicedDate` we can validate and show when the order was invoiced.
1. Go to [GraphiQL](https://troca--tokstok.myvtex.com/_v/acupula.tokstok-troca-e-devolucao@0.1.0/graphiql/v1?operationName=order&query=query%20order%20%7B%0A%20%20%20%20order(id%3A%20%22882823036831-01%22)%20%7B%0A%20%20%20%20%20%20%09invoicedDate%0A%20%20%20%20%7D%20%0A%7D)(link with the order query and order ID)
> Add invoicedDate to Order type

- CHANGELOG.md
- graphql/types/Shipping.graphql
Make `selectedSla` available in `LogisticInfo` type;
Some apps need to validate and display which delivery method was selected.
1. Follow this [GraphiQL](https://selectedmethod--tokstok.myvtex.com/_v/vtex.store-graphql@2.80.3/graphiql/v1?operationName=order&query=query%20order%20%7B%0A%20%20order(id%3A%20%22939031623492-01%22)%20%7B%0A%20%20%20%20shippingData%20%7B%0A%20%20%20%20%20%20logisticsInfo%20%7B%0A%20%20%20%20%20%20%20%20selectedSla%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) link;
2. This page is ready with the query and the order ID.
> Add `selectedSla` to `LogisticInfo` type

- CHANGELOG.md
- README.md
- graphql/schema.graphql
- graphql/types/PageType.graphql
- node/clients/catalog.ts
- node/resolvers/catalog/index.ts
- node/resolvers/catalog/utils.ts
The current algorithm to discover page type needs to fetch brand list and category tree, which can be huge, throwing timeouts or increasing the latency.
You can try it here: https://pagetype--storecomponents.myvtex.com/_v/vtex.store-graphql@2.87.1/graphiql/v1?query=%7B%0A%20%20pageType(path%3A%20%22%2Felectronics%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20type%0A%20%20%7D%0A%7D
---|---
_ | Bug fix 
✔️| New feature 
> Create new pagetype query

- node/resolvers/catalog/product.ts
GoCommerce allow users to save products without categories, but VTEX doesn't, so we send a generic category (`/Home/`) when editing a product. This category will be returned by the search api, but not by the category api, because it doesn't exist on the product. The result is that the store front receives an array with a `null`, causing a break (example: https://mystore.mygocommerce.com/teste-produto/p).
https://augusto--mystore.mygocommerce.com/variacoes/p
---|---
✔️ | Bug fix 
> Fix category tree when product has no category

- CHANGELOG.md
- node/resolvers/catalog/index.ts
When using the `product` query, we could specify if we wanted to get the product by it's `slug` or by other parameters (`ProductUniqueIdentifier`). If both `slug` and `ProductUniqueIdentifier` are sent, `slug` was the default method of retrieving the product. 
This PR changes this behavior and adds preference to the `ProductUniqueIdentifier`
---|---
_ | Bug fix 
> Uses raw slug as fallback in product query

- CHANGELOG.md
- node/resolvers/checkout/index.ts
`marketingTags`, in some scenarios, were being passed as `null`. This caused an error the Checkout backend.
> `"Object reference not set to an instance of an object."`
[Workspace](https://breno--storecomponents.myvtex.com/?utm_source=foo)
Click to add an item to cart.
n/a
---|---
✔️ | Bug fix 
> Avoid passing wrong value of marketingTags to Checkout

- CHANGELOG.md
- node/resolvers/catalog/offer.ts
When the product have no payment method an error explodes:
> TypeError: Cannot read property 'NumberOfInstallments' of null
The issue:
[Workspace](https://nardi--pilateslovers.myvtex.com/)
---|---
✔️ | Bug fix 
> Fix installments returning array with null

- CHANGELOG.md
- graphql/types/Brand.graphql
- node/resolvers/catalog/brand.ts
This PR fixes the `titleTag` prop that was replaced with `title` in  the `Brand` type (#380).
---|---
✔️ | Bug fix 
> Fix Brand titleTag

- CHANGELOG.md
- node/package.json
- node/resolvers/catalog/index.ts
- node/utils/ioMessage.ts
- node/yarn.lock
The client messages shouldn't be used by store-graphql in order to translate slugs before sending them to search-api. In fact, this old translate route will be removed soon and thus only the translate method from messagesGraphQL client should be used.
---|---
_ | Bug fix 
✔️ | Technical improvements
> Call messagesGraphQL client to translate instead of messages

- CHANGELOG.md
- graphql/types/Shipping.graphql
- node/resolvers/checkout/index.ts
- node/resolvers/checkout/shipping.ts
- node/typings/Checkout.ts
Fixes https://app.clubhouse.io/vtex/story/19689/pickup-point-id-shouldn-t-show-on-shipping-simulator
When the SLA is a pickup point, its name value was displaying a weird value with ID.
Solution: create a friendlyName resolver that outputs the correct value depending on the SLA. For now, the only variation is with pickup point, it will get the friendlyName from the pickupStoreInfo object.
https://fidelis--paguemenos.myvtex.com/clareador-facial-active-unify-isdin-fps99-sem-cor-50ml/p
---|---
_ | Bug fix 
> create friendlyName resolver

- CHANGELOG.md
- node/globals.ts
- node/resolvers/profile/fieldResolvers.ts
- node/resolvers/profile/services.ts
Every address related front-end code uses `geoCoordinates` (plural), but the MasterData accepts only `geoCoordinate` (singular). Currently, every query returns `null` for the `geoCoordinates` value.
https://kiwi--storecomponents.myvtex.com/account#/addresses/new
https://kiwi--storecomponents.myvtex.com/_v/private/vtex.store-graphql@2.105.2/graphiql/v1?operationName=Addresses&query=query%20Addresses%20%40context(scope%3A%20%22private%22)%20%7B%0A%20%20profile%20%7B%0A%20%20%20%20cacheId%0A%20%20%20%20addresses%3A%20address%20%7B%0A%20%20%20%20%20%20addressId%3A%20id%0A%20%20%20%20%20%20addressType%0A%20%20%20%20%20%20addressName%0A%20%20%20%20%20%20city%0A%20%20%20%20%20%20complement%0A%20%20%20%20%20%20country%0A%20%20%20%20%20%20neighborhood%0A%20%20%20%20%20%20number%0A%20%20%20%20%20%20 …
> Transform geoCoordinates into geoCoordinate when creating address

- node/service.json
Add cpu to service.json.
I am being conservative now.
The idea is that app's maintainers will be able to manually tune this parameter.
IO Platform team will soon provide an automated way to optimize these kind of parameters, e.g., cpu, minReplicas, etc.
cpu unit is a percentage of total CPU time.
cpu should be larger or equal than 5 and smaller or equal than 80.
IO will scale your app in order to keep the average CPU usage close to the cpu provided in service.json.
minReplicas/maxReplicas have precedence over the scaling policy.
Considering the maxReplicas parameter, if your app tries to use more CPU than it requested then IO will try to accommodate that demand, but will not guarantee.
You can check your app's metrics here: [grafana](http://grafana.ingress.vtex.io/d/0FbY1kRWk/io-deployment …
> add cpu to service.json

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/checkout.ts
- node/resolvers/checkout/index.ts
- node/resolvers/session/sessionResolver.ts
- node/typings/Checkout.ts
- node/typings/Session.ts
1. Store uses a Locale Switcher
2. User change the language from English to Portuguese
3. User goes to Checkout page
4. Checkout page is in English
This PR changes the orderForm data to change the user language to the one selected in the its session.
So, in the scenario above the user would encounter the Checkout page in Portuguese.
1. Open the store
2. Add something to the cart
3. Open the Checkout page
4. See that Checkout uses the default language of the store
5. Go back to the store
6. Depending on the store do:
6.1 **Store Components:** Add the query string `?cultureInfo=pt-BR`
6.2 **Spazio Lusso:** Change the language to English using the Locale Switcher
7. Open the Checkout page
8. Check if the language is right
[Spazio Lusso, store with Locale …
> Sync OrderForm locale with the locale currently being used by the store

- node/service.json
Decrease CPU to 30.
The idea is that app's maintainers will be able to manually tune this parameter.
cpu unit is a percentage of total CPU time.
cpu should be larger or equal than 5 and smaller or equal than 80.
IO will scale your app in order to keep the average CPU usage close to the cpu provided in service.json.
minReplicas/maxReplicas have precedence over the scaling policy.
Considering the maxReplicas parameter, if your app tries to use more CPU than it requested then IO will try to accommodate that demand, but will not guarantee.
---|---
_ | Bug fix 
> decrease cpu to 30

- CHANGELOG.md
- node/directives/withSegment.ts
- node/package.json
- node/yarn.lock
Avoid calling getSegment API. Decode segment from token locally.
https://segment--storecomponents.myvtex.com/
---|---
_ | Bug fix 
> decode segment token locally

- CHANGELOG.md
- graphql/types/Profile.graphql
- node/resolvers/profile/index.ts
Previously it was not possible to verify if the user was not allowed because it was not logged in or if it was forbidden.
1. Open https://breno--gympassus.myvtex.com/
2. Log in with a Brazilian account
3. Be redirected to `/error-sign-up`
---|---
_ | Bug fix 
> Add condition field to checkProfileAllowed query

- CHANGELOG.md
- node/clients/catalog.ts
- node/resolvers/profile/index.ts
Previously we would short circuit the allowed check if the user is not logged in and return `unauthorized`.
Now if the user is not logged in, we still check for open Trade Policies. If the current Trade Policy is open, we return `authorized`. 
Working in a closed Trade Policy (no regression)
https://breno--gympassus.myvtex.com/
Working in an open Trade Policy (new scenario)
https://breno--powerplanet.myvtex.com/
- [ x Deleted the workspace after merging this PR (if applicable).
n/a
---|---
✔️ | Bug fix 
> Allow not logged in users to visit open trade policies

- CHANGELOG.md
- node/clients/index.ts
- node/clients/session.ts
- node/resolvers/profile/index.ts
- node/resolvers/session/index.ts
- node/utils/vtexId.ts
https://fidelis2--storecomponents.myvtex.com/_v/private/vtex.store-graphql@2.115.0/graphiql/v1?query=mutation%20%7B%0A%20%20savePickupInSession(name%3A%20%22teste2%22%2C%20address%3A%20%7BaddressId%3A%22teste3%22%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20favoritePickup%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%23%20query%20%7B%0A%23%20%20%20getSession%7B%0A%23%20%20%20%20%20id%0A%23%20%20%20%20%20adminUserId%0A%23%20%20%20%7D%0A%23%20%7D
---|---
_ | Bug fix 
> fix update session logging user out

- node/__tests__/checkout/index.test.ts
This fixes checkout tests not working because mockContext does not have `vtex.orderFormId`
---|---
✔️ | Bug fix 
✔️ | Technical improvements
> Fix checkout tests #trivial

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/masterdata.ts
- node/resolvers/document/index.ts
Add query to fetch public schema from Master Data V2
[Workspace](https://helena--storecomponents.myvtex.com/_v/private/vtex.store-graphql@2.116.1/graphiql/v1?query=%7B%0A%20%20documentPublicSchema(dataEntity%3A%20%22Test%22%2C%20schema%3A%20%22personV2%22)%20%7B%0A%20%20%20%20schema%0A%20%20%7D%0A%7D%0A)
---|---
_ | Bug fix 
> Implement query documentPublicSchema to fetch public schemas from MD

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/checkout.ts
- node/package.json
- node/resolvers/checkout/index.ts
- node/resolvers/session/index.ts
- node/yarn.lock
Clear OrderForm data when a Telemarketing user logout from a customer account
1. Enter https://dev14101--unimarcdev.myvtex.com/
2. Login with the user "casenssi@gmail.com"
3. Add a product to Cart
4. Logout the customer account on the telemarketing's logout button
_ | Bug fix 
Discuss link: https://github.com/vtex-apps/store-discussion/issues/228
> Clear OrderForm data when a Telemarketing user logout from a customer account

- CHANGELOG.md
- docs/README.md
- graphql/types/Order.graphql
When a user wants to retrieve the last order of a user, the name of the field containing the state of the order is status. This contribution also adds the field `statusDescription` as well
A customer in Spain wanted to use the `userLastOrder` query, but it was not retrieving the `status` field correctly.
[test](https://devdocs--demostore.myvtex.com/)
---|---
✔️ | Bug fix 
I was confused about the decision if it is better to have one `state` variable that is smart to check if it has `status` or `state` as response. What do you think about it?
> Add status and statusDescription as Order fields

- CHANGELOG.md
- graphql/schema.graphql
Related https://github.com/vtex-apps/store-graphql/issues/182
Deprecate logout mutation. 
The VTEX ID team recommended against having this mutation ([see Slack thread](https://vtex.slack.com/archives/C90SGTR6U/p1586896034305000))
https://breno--storecomponents.myvtex.com/_v/private/vtex.store-graphql@2.120.1/graphiql/v1?query=mutation%20%7B%0A%20%20logout%0A%7D
---|---
✔️ | Bug fix 
> Deprecate mutation logout

- CHANGELOG.md
- graphql/types/OrderForm.graphql
Adds `sellers` attribute for the orderForm schema
[https://sellersattribute--codeby.myvtex.com/_v/private/vtex.store-graphql@2.120.2/graphiql/v1?operationName=orderForm](https://sellersattribute--codeby.myvtex.com/_v/private/vtex.store-graphql@2.120.2/graphiql/v1?operationName=orderForm)
Use the following query to retrieve the expected information:
```
query orderForm {
orderForm {
sellers {
id
name
}
}
}
```
---|---
_ | Bug fix 
✔️ | Breaking change 
> Add sellers attribute to OrderForm

- CHANGELOG.md
- node/resolvers/catalog/category.ts
Possibly due to an issue in catalog, category urls were being answered with http and were not being erased by the resolver.
https://adkjhsadks--minisomx.myvtex.com/
---|---
_ | Bug fix 
> fix category http regex

- CHANGELOG.md
- node/resolvers/checkout/attachmentsHelper.ts
When we add more than one SKU to the cart it splits into two or more columns and the one who was split loses its attachment value. 
What is odd is when we just add one, go to the cart, and at the cart change the item quantity to more than two it works fine. That's why I believe it is something related to the action to add to the cart.
Add this item to the cart, with a quantity greater than 1, and the items 
[Workspace](https://oldminicartdebug--worldwidegolf.myvtex.com/titleist-pro-v1-enhanced-alignment-custom-golf-balls-600000755/p?skuId=6002994)
---|---
✔️ | Bug fix 
This is related to this Slack thread: https://vtex.slack.com/archives/C9P4RMW6Q/p1589406757496000
> Fix items with assembly options being added to the OrderForm and getting split

- CHANGELOG.md
- node/directives/withCurrentProfile.ts
- node/resolvers/session/index.ts
- node/resolvers/session/service.ts
- Reduce number of errors on the session API:
- http://monitoring.vtex.com/api/pvt/evidence?app=session&hash=c0d0df45e40d6cd0f0800415064bf80d
- remove the `vtex_session` cookie and execute the query
[Workspace](https://felipe--recorrenciaqa.myvtex.com/_v/private/vtex.store-graphql@2.123.3/graphiql/v1?query=query%20%7B%0A%20%20getSession%20%7B%0A%20%20%20%20address%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)
---|---
_ | Bug fix 
> Avoid calling session if no cookie is present

- CHANGELOG.md
- graphql/types/Product.graphql
- node/resolvers/catalog/offer.ts
Add spotPrice as it was done in:
https://github.com/vtex-apps/search-graphql/pull/70
https://github.com/vtex-apps/search-graphql/pull/72
(I copied from the code in master, not from the PRs)
We need this feature in store-graphql because stores in vtex.store@1.x use store-graphql instead of search-graphql.
Related to PR https://github.com/vtex-apps/store/pull/470
https://breno--storecomponents.myvtex.com/_v/private/vtex.store-graphql@2.123.4/graphiql/v1?operationName=Product&variables=%7B%0A%20%20%22slug%22%3A%20%22classic-shoes%22%0A%7D
---|---
_ | Bug fix 
> Add field spotPrice

- CHANGELOG.md
- graphql/types/Order.graphql
Have access to the custom data information on order graphql 
[Graphql](https://liquid--destdiscount.myvtex.com/_v/private/vtex.store-graphql@2.123.4/graphiql/v1?operationName=order&query=query%20order(%24id%3A%20String!)%20%7B%0A%09order(id%3A%20%24id)%20%7B%0A%20%20%20%20allowCancellation%20%0A%20%20%20%20salesChannel%0A%20%20%20%20customData%20%7B%0A%20%20%20%20%20%20customApps%20%7B%0A%20%20%20%20%20%20%20%20fields%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%09%7D%0A%7D%0A&variables=%7B%0A%09%22id%22%3A%20%221041891542562-01%22%0A%7D%0A)
---|---
_ | Bug fix 
✔️| New feature 
> Add field `CustomData` in Order Graphql

- CHANGELOG.md
- graphql/schema.graphql
- node/__tests__/checkout/index.test.ts
- node/resolvers/checkout/index.ts
Currently, there is two ways to provide the orderFormId which an mutation related to the cart will operate on. The first is the `orderFormId` parameter which exists in all of these mutations, and the other is to provide a `checkout.vtex.com` cookie with the format `__ofid=XXX` (where `XXX` is the actual order form ID).
This inconsistency can cause (and has caused) some issues where you would supply both the cookie and the parameter to the mutation but those two values weren't the same. With this, we would be operating (e.g. adding a product) to a different cart than what the user is seeing on the store. Also, when they effectively go to checkout, the order form they'll see is the one which the value in the cookie references, not whatever the minicart provides in the mutation argument, …
> CHK-104: Remove orderFormId parameter from checkout mutations

- CHANGELOG.md
- graphql/types/Shipping.graphql
In one of our customizations we have a simulation to a lot of sellers and we have to ordenated each ones and send to each components the respectives logisticItems, and the only way to do that is identificate each logisticItem with its logisticInfo.
https://gus--carrefourbrqa.myvtex.com/admin/graphql-ide
variables:
```json
{
"shippingItems": [
{ "id": "310118535", "quantity": "1", "seller": "5993" },
{ "id": "310118535", "quantity": "1", "seller": "4642" }
],
"country": "BRA",
"postalCode": "12942-210"
}
```
query:
```graphql
query SIMULATE_SHIPPING($shippingItems: [ShippingItem], $postalCode: String, $country: String) {
shipping(items: $shippingItems, postalCode: $postalCode, country: $country) {
items {
seller
}
logisticsInfo {
itemIndex
slas {
id
name
price
shippingEstimate …
```
> LogisticItem type on shipping query

- CHANGELOG.md
- manifest.json
- node/resolvers/catalog/category.ts
- node/utils/i18n.ts
Currently any translatable prop is not returning with the correct formatting, causing some data to not be translated. This PR fixes it for the categories, since it is used by the app `vtex.category-menu` and causing issues for cross-border stores.
This can be tested by making any category request in a different binding. An easy way is going to this page in this workspace:
https://fox--powerplanet.myvtex.com/smartphones-e-acessorios?__bindingAddress=b2c.powerplanet.com/pt
and check if the category menu is translated
---|---
_ | Bug fix 
> Translates correctly categories result

- CHANGELOG.md
- manifest.json
- node/clients/catalog.ts
- node/clients/index.ts
- node/clients/rewriter.ts
- node/package.json
- node/resolvers/catalog/category.ts
- node/yarn.lock
Currently the slug and href fields from the Category type were not being translated according to the user's binding this caused a problem in the category menu component where the text of the menu item was translated but when clicked it sent the user to the page in the default language.
You can test the category menu component  that uses the categories query:
https://fox--powerplanet.myvtex.com/toys---hobbies?__bindingAddress=b2c.powerplanet.com/fr
All menu items should send you to the translated url
---|---
_ | Bug fix 
> Translates categories slug and href

- CHANGELOG.md
- node/resolvers/catalog/category.ts
In the multiple binding case, when there isn't a translation for the route the fallback was the incoming url, meaning it had the full `{{account}}.vtexcommercestable.com.bt` host and not only the path.
You can do a category query and check the href property
https://fox--minisocl.myvtex.com/
---|---
_ | Bug fix 
> Fix href fallback

- CHANGELOG.md
- graphql/schema.graphql
- graphql/types/Profile.graphql
- node/globals.ts
- node/package.json
- node/resolvers/profile/index.ts
- node/yarn.lock
Enables users to save the name of clients subscribing to a newsletter. 
Go to this [Workspace](https://newsletter--storecomponents.myvtex.com/_v/private/vtex.store-graphql@2.133.0/graphiql/v1?operationName=subscribeNewsletter&query=mutation%20subscribeNewsletter(%24email%3A%20String%2C%20%24fields%3A%20NewsletterFieldsInput)%20%7B%0A%20%20subscribeNewsletter(email%3A%20%24email%2C%20fields%3A%20%24fields)%0A%7D%0A&variables=%7B%0A%20%20%22email%22%3A%20%22test%40vtex.com.br%22%2C%0A%09%22fields%22%3A%20%7B%0A%20%20%20%20%22name%22%3A%20%22Person%22%2C%0A%20%20%20%20%22phone%22%3A%20%22%2B11111111%22%0A%20%20%7D%20%20%0A%7D) and perform the following mutation: 
```graphql
mutation subscribeNewsletter($email: String, $fields: NewsletterFieldsInput) {
subscribeNewsletter(email: $email, …
```
> Add 'name' argument to 'subscribeNewsletter' mutation

- CHANGELOG.md
- node/utils/simulation.ts
Fills the `PriceWithoutDiscount` field in the `itemsWithSimulation` query.
Use `sellingPrice` instead of `price` in the `itemsWithSimulation` query.
```
curl --request POST \
--url 'https://pricewithoutdiscount--storecomponents.myvtex.com/_v/segment/graphql/v1?workspace=pricewithoutdiscount' \
--header 'Content-Type: application/json' \
--data '{"query":"{\n  itemsWithSimulation(items: [{itemId: \"20\", sellers: [{sellerId: \"1\"}]}]) {\n    sellers {\n      commertialOffer {\n        Price\n        PriceWithoutDiscount\n      }\n    }\n  }\n}\n"}'
```
---|---
✔️ | Bug fix 
> fix pricewithoutdiscount and price

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
We are not setting a `maxAge` for the `orderForm` query, so the platform adds the default value (long). We should explicitly set its value to `ZERO` to avoid caching sensitive information by mistake.
https://bacelar--muji.myvtex.com/?__bindingAddress=www.mujionline.eu/uk
Open Chrome DevTools, filter the requests with `/_v/private`, and check if all the requests with `orderForm` have `maxAge=zero` in the query string.
---|---
_ | Bug fix 
✔️ | Technical improvements
> Remove orderForm cache

- CHANGELOG.md
- manifest.json
- node/clients/masterdata.ts
Test [here](https://lucis--vtexufcg.myvtex.com/_v/private/vtex.store-graphql@2.136.2/graphiql/v1?query=mutation%20a%20%7B%0A%20%20updateDocument(acronym%3A%20%22CL%22%2C%20document%3A%7B%20fields%3A%20%5B%7Bkey%3A%20%22id%22%2C%20value%3A%20%22b%22%7D%5D%7D%2C%20schema%3A%22v1%22)%7B%0A%20%20%20%20id%0A%20%20%7D%0A%7D&operationName=a)
> Adding dataentites as a prefix on all endpoints of Master Data client

- manifest.json
This app is calling `portal.vtexcommercebeta.com.br`, but there is no policy that allows this access. It currently depends on another of its policies that is giving out too broad permissions that we are going to fix soon, so I am adding the policy that will replace it.
I am running a script to simulate the permissions the app will have once the bad policy is fixed.
---|---
✔️ | Bug fix 
> Add policy to call portal.vtexcommercebeta.com.br

- CHANGELOG.md
- node/clients/catalog.ts
Remove special characters from Search API.
https://brenovtex--motorolaus.myvtex.com/edge+?_q=edge%20&map=ft
Instead of calling this:
https://motorolaus.vtexcommercestable.com.br/api/catalog_system/pub/products/search/edge+?&O=OrderByPriceDESC&map=ft&_from=0&_to=8
It will call this:
https://motorolaus.vtexcommercestable.com.br/api/catalog_system/pub/products/search/edge?&O=OrderByPriceDESC&map=ft&_from=0&_to=8
> Remove special characters from Search

- CHANGELOG.md
- graphql/schema.graphql
We've released a hot fix on our framework to always fallback to private queries, what causes workspaces with unannotated queries to fail on SSR.
This query, specifically, seemed to affect the largest number of accounts due `vtex.store-form` app.
https://vtex.slack.com/archives/C9P4RMW6Q/p1607110252253000
> Explicitly adding public scope to public queries

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
Motivation: [this PR](https://github.com/vtex-apps/render-runtime/pull/589) changed how we _fetch_ our GraphQL queries when they're not annotated. As an end result, unannotated queries (like these ones) that before were going via `GET` requests are now using `POST`.
That is not ideal for two reasons:
- It's _non-SSRable_.
- It's not cacheable on CDN
Here, we explicitly annotate such queries.
> Adding scope: public to Master Data queries

- CHANGELOG.md
- graphql/types/Shipping.graphql
Changes introduced by https://github.com/vtex-apps/store-graphql/pull/524 could cause build fails on apps that import GraphQL types from `vtex.store-graphql`. This PR aims to revert those changes.
[Workspace](https://victormiranda--storecomponents.myvtex.com/_v/private/vtex.store-graphql@2.138.1/graphiql/v1)
> Bring back 'pickupStoreInfo' type to app's schema

- CHANGELOG.md
- node/utils/simulation.ts
When we use the async price, we need to have the `AvailableQuantity` information. For while, the IS doesn't have the exact quantity value, that's why we use the hardcoded values `? 0 : 10000`. We are doing the same [here](https://github.com/vtex-apps/search-resolver/blob/v1.x/node/commons/compatibility-layer.ts#L228)
[Workspace](https://hiago--carrefourbrfood.myvtex.com/)
1. Scroll the page until you are able to see a product price
2. Open the Apollo the dev tools and check the `itemsWithSimulation` query
https://github.com/vtex-apps/store-resources/pull/149
> add avalable quantity

- CHANGELOG.md
- node/resolvers/catalog/brand.ts
We are slugifying different than catalog on store-graphql, when the right behavior should be using same as catalog, causing unexpected behaviors when calling this query with the wrong slug:
https://github.com/vtex-apps/store-graphql/blob/e4a1bec686dc04c42c60c8e51da9f5f04bef07f7/node/resolvers/catalog/slug.ts#L26-L27
Go to the workspace
Select store-graphql app
Try the following query:
```
query{
brand(id:2000105){
id
name
slug
cacheId
}
}
```
[Workspace](https://iespinoza--equishopper.myvtex.com/admin/graphql-ide)
What we were doing
What we should do
The fix with this PR
Zendesk: #340592
> fix: brand slugify same as catalog

- CHANGELOG.md
- docs/README.md
- graphql/schema.graphql
- graphql/types/LoginSessionsInfo.graphql
- node/package.json
- node/resolvers/auth/index.ts
- node/resolvers/auth/mapLoginSessionsFromAPI.ts
- node/resolvers/auth/types.ts
- node/resolvers/headers.ts
- node/resolvers/paths.ts
- node/resolvers/profile/services.ts
- node/yarn.lock
Add `loginSessionsInfo` query to graphql
This also refactors a piece of `node/resolvers/auth/index.ts` to improve code quality and consistency.
The fields returned by `loginSessionsInfo` satisfy [this design](https://www.figma.com/file/6rplh1huI6IpzRfaCnv0SD/Sessions-Manager---MyAccount?node-id=1%3A15).
Check out [this query](https://rafaprtest7--storecomponents.myvtex.com/_v/private/vtex.store-graphql@2.136.6/graphiql/v1?operationName=loginSessions&query=query%20loginSessions%20%7B%0A%20%20loginSessionsInfo%20%7B%0A%09%09currentLoginSessionId%0A%20%20%20%20loginSessions%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20cacheId%0A%20%20%20%20%20%20deviceType%0A%20%20%20%20%20%20city%0A%20%20%20%20%20%20lastAccess%0A%20%20%20%20%20%20browser%0A%20%20%20%20%20%20os%0A%20%20%20%20%20%20ip%0A%2 …
> Feature/idcs 40/login sessions

- CHANGELOG.md
- docs/README.md
- graphql/schema.graphql
- node/resolvers/auth/index.ts
- node/resolvers/paths.ts
This adds the mutation `logOutFromSession`. It allows a user to log out from another device remotely.
First, log in to the admin and store [here](http://rafaprtest7--storecomponents.myvtex.com/login).
Do that again in a different device/browser (example: your phone)!
Then, look at the results of [this query](https://rafaprtest7--storecomponents.myvtex.com/_v/private/vtex.store-graphql@2.140.0/graphiql/v1?query=query%20%7B%0A%20%20loginSessionsInfo%20%7B%0A%20%20%20%20currentLoginSessionId%0A%20%20%20%20loginSessions%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20cacheId%0A%20%20%20%20%20%20deviceType%0A%20%20%20%20%20%20city%0A%20%20%20%20%20%20lastAccess%0A%20%20%20%20%20%20browser%0A%20%20%20%20%20%20os%0A%20%20%20%20%20%20ip%0A%20%20%20%20%20%20fullAddress%0A%20%20%20%20%20%20firstAcc …
> Feature/idcs 67/log out from session

- CHANGELOG.md
- node/resolvers/profile/services.ts
The `vcs-checkout` endpoint in the profile system may return no `availableAccounts`. The value of this variable wasn't null-checked before passing it to `JSON.parse`
[Workspace](https://arthur--adereautoservico.myvtex.com/)
Before:
After:
> Fix passing undefined to JSON.parse in the profile query getPayments

- CHANGELOG.md
- node/dataSources/identity.ts
- node/directives/withCurrentProfile.ts
- node/resolvers/paths.ts
- node/resolvers/profile/index.ts
Add authorization to subscribeNewsletter resolver.
Fulfill the `<YOUR COOKIE HERE>` with your browser cookie and <BASE64 VARIABLES> with encoded base64 object with this pattern `"{\"isNewsletterOptIn\":true,\"email\":\"user-email-here\"}"`
```
curl --location --request POST 'https://brasileiro--storecomponents.myvtex.com/_v/private/graphql/v1?workspace=brasileiro&maxAge=long&appsEtag=remove&domain=store&locale=en-US&__bindingId=aacb06b3-a8fa-4bab-b5bd-2d654d20dcd8' \
--header 'pragma: no-cache' \
--header 'cache-control: no-cache' \
--header 'accept: */*' \
--header 'content-type: application/json' \
--header 'accept-language: pt,en-US;q=0.9,en;q=0.8,pt-PT;q=0.7' \
--header 'cookie: <YOUR COOKIE HERE>' \
--data-raw '{"operationName":"subscribeNewsletter","variables":{},"extensions":{"persi …
```
> Add authorization to subscribeNewsletter resolver

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/checkout.ts
Currently the `itemsWithSimulation` query has a `private` scope this setting is causing a lot of unnecessary requests to the simulation API. This PR changes from `private` to the `segment` scope.
Also, it adds the `x-vtex-user-agent` header to the checkout calls, which is important to track the call origin.
[Workspace](https://hiago--carrefourbr.myvtex.com/)
Go to any PLP. The product prices are being returned by the `itemsWithSimulation` query.
> change itemsWithSimulation scope and add x-vtex-user-agent

- CHANGELOG.md
- node/utils/simulation.ts
In the `itemsWithSimulation` query, the `sellerId` was being set with the value of the item ID:
[Workspace](https://regionalization--carrefourbr.myvtex.com/busca/galaxy%20tab%20a%20t290?&map=ft)
> Fix seller id

- CHANGELOG.md
- node/clients/session.ts
Session cookie being extracted in a safe manner.
The session cookie extraction relied on the fact that the responses always came with the Set-Cookie header.
When Janus stopped setting its janus-sid cookie, there was no Set-Cookie present in the response.
This caused IO to be down for almost an hour.
- [Als](https://victormiranda--alssports.myvtex.com/clothing/hoodies---sweatshirts/Womens?map=c,c,specificationFilter_7721)
- [Umbro](https://victormiranda--umbro.myvtex.com/)
- [Store Components](https://victormiranda--storecomponents.myvtex.com/apparel---accessories/)
- [Red Oxx](https://victormiranda--redoxx.myvtex.com/)
- [New Balance](https://victormiranda--newbalance.myvtex.com/tenis-new-balance-574-casual-masculino-ml574bi2/p?skuId=387084)
- [Motorola …
> Update cookie extraction

- CHANGELOG.md
- graphql/types/OrderForm.graphql
- node/typings/Checkout.ts
Add checkout API priceDefinition structure
[Workspace](https://pricedefinition--vtexproject.myvtex.com/_v/private/vtex.store-graphql@2.143.1/graphiql/v1?query=query%20%7B%0A%20%20searchOrderForm%20(%0A%20%20%20%20orderFormId%3A%2278f1aa981882432993c6877bbaa7fdd2%22%0A%20%20)%20%7B%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20sellingPrice%0A%20%20%20%20%20%20priceDefinition%20%7B%0A%20%20%20%20%20%20%20%20calculatedSellingPrice%0A%20%20%20%20%20%20%20%20sellingPrices%20%7B%0A%20%20%20%20%20%20%20%20%20%20quantity%0A%20%20%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20total%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)
> Added priceDefinition structure

- CHANGELOG.md
- graphql/types/Shipping.graphql
A T1 customer wants to show the distance from the customer to the Store, this PR adds this field to a type we're using on the App, the information is already available by the API and resolver, no need to do extra development
[Workspace](https://wender--eriksbikeshop.myvtex.com/_v/private/vtex.store-graphql@2.145.1/graphiql/v1?variables=%7B%0A%20%20%22items%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22quantity%22%3A%20%221%22%2C%0A%20%20%20%20%20%20%22id%22%3A%20%228055383%22%2C%0A%20%20%20%20%20%20%22seller%22%3A%20%221%22%0A%20%20%20%20%7D%0A%20%20%5D%2C%0A%20%20%22postalCode%22%3A%20%2255408%22%2C%0A%20%20%22country%22%3A%20%22USA%22%0A%7D&operationName=getShippingEstimates&query=query%20getShippingEstimates(%24items%3A%20%5BShippingItem%5D%2C%20%24postalCode%3A%20String%2C%20%24 …
> [USAAPPTEAM-32] Show distance on pickup

- CHANGELOG.md
- node/resolvers/checkout/index.ts
This PR fixes two problems:
1. When the simulation API returns an error the `store-graphql` request get stuck until it hits the timeout. This is happening because the error is throw inside a promise.
2. When there is more than one seller and one of them returns an error, the `itemsWithSimulation` query is not returning any of them.
[Workspace](https://hiago--rihappynovo.myvtex.com/)
> handle error on itemsWithSimulation

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/clients/profile.ts
- node/directives/withCurrentProfile.ts
- node/resolvers/profile/index.ts
- node/resolvers/profile/services.ts
- node/utils/allowListAccounts.ts
- node/utils/trustedAccounts.ts
This PR adds a new feature that allows the setup of trusted accounts. To accomplish this feature, this pr adds:
- trustedAccounts app settings
- trustedAccounts on withCurrentProfile and newsletter
[Workspace](https://storetheme.vtex.com?workspace=brasileiro)
Try to fetch profile data from different users.
> Add trustedAccounts to settingsSchema

- CHANGELOG.md
- graphql/schema.graphql
- node/resolvers/profile/index.ts
Allow new users subscribe to the newsletter without being authenticated.
[Workspace](https://storetheme.vtex.com/?workspace=brasileiro)
> fix: Remove withCurrentProfile directive from subscribeNewsletter mutation

- CHANGELOG.md
- graphql/types/Profile.graphql
- manifest.json
- node/clients/index.ts
- node/clients/licenseManagerExtended.ts
- node/clients/profile/index.ts
- node/clients/profile/profileV1.ts
- node/clients/profile/profileV2.ts
- node/clients/profile/profileV2EU.ts
- node/clients/profile/profileV2US.ts
- node/directives/withCurrentProfile.ts
- node/globals.ts
- node/resolvers/profile/fieldResolvers.ts
- node/resolvers/profile/index.ts
- node/resolvers/profile/services.ts
This PR adds a Profile System V2 client. This new Profile System is the one that supports PII protection. The way we are using it is transparent to the end-user. There's some back and forth data translation because of it.
https://profilesystempii--qastoreeu.myvtex.com/_secure/account/orders#/profile
To query for the data (and then know that is PII enabled), you can use [the Profile System V2 API](https://profile-system-beta.vtex.systems/docs/profile-system/swagger/index.html#/) and look for your user email.
There are no UI changes on this one.
> Adding new PII Profile System Support

- CHANGELOG.md
- node/clients/profile/index.ts
- node/clients/profile/profileV1.ts
- node/clients/profile/profileV2.ts
- node/globals.ts
This PR writes the newsletter option in the correct place
Use this [Workspace](https://newsletter--qastoreeu.myvtex.com/_secure/account/orders#/profile) and toggle your newsletter preference.
It will be saving in your purchase info in the new Profile System. Link for the Profile System query if you don't belive me in link 1 (you got to find out your user id in it to get it. See link 2. More trouble then it's worth it, I know...)
Link 1: Fetching purchase info -> GET https://portal.vtexcommercestable.com.br/api/storage/profile-system/profiles/<your-user-id>/purchase-info?an=qastoreeu
Link 2: Fetching your user profile -> GET https://portal.vtexcommercestable.com.br/api/storage/profile-system/profiles/<your-email>/?an=qastoreeu&alternativeKey=email
> Writing newsletter option to the correct place

- CHANGELOG.md
- node/typings/Catalog.ts
- node/utils/simulation.ts
We are having Price divergences between PDP and checkout with search queries:
Price nowadays is being calculated in the following way: `SellingPrice / (unitMultiplier * 100)`, and this is not accurate. Sometimes when the unit multiplier is an integer value or maybe duo coincidence you will have the price matching, but, when the price is float, the price won't be accurate in most the cases and you will have the discrepancy of cents
So, to fix it, the correct value of price should be price/100, we will have the same value of the checkout API
[PDP:](https://master--gbarbosaqa.myvtex.com/manga-rosa-kg/p) 
[Search without fix:](https://master--gbarbosaqa.myvtex.com/hortifruti) 
[Search with fix:](https://rbussola--gbarbosaqa.myvtex.com/hortifruti) 
Other examples at zonasul, products: …
> fix: price should consider orderForm price instead of sellingPrice with unitMultiplier

- CHANGELOG.md
- node/utils/simulation.ts
InterestRate as integer in simulation API
The simulation API display this value as an integer, duo that, we are displaying wrongly the interest rate on the search side
[With the fix](https://iespinoza--omnilink.myvtex.com/omniturbo?_q=Omniturbo&map=ft)
[Without the fix](https://iespinoza2--omnilink.myvtex.com/omniturbo?_q=Omniturbo&map=ft)
Checking simulation call:
```
curl --request POST \
--url 'https://omnilink.vtexcommercestable.com.br/api/checkout/pvt/orderForms/simulation?sc=1' \
--header 'Content-Type: application/json' \
--header 'VtexIdclientAutCookie: xx' \
--data '{"items":
[{
"id":"2",
"quantity": 1,
"seller": "1"
}],
"shippingData":
{
"logisticsInfo":
[{
"regionId":""
}]
}
}'
```
SOLR Search API: 
`https://omnilink.vtexcommercestable.com.br/api/catalog_system/pub/products/sear …
> fix: InterestRate should be in its percet format

- CHANGELOG.md
- node/typings/Checkout.ts
- node/utils/simulation.ts
We are having Price divergences between PDP and checkout with search queries:
Price nowadays is being calculated in the following way: `SellingPrice / (unitMultiplier * 100)`, and this is not accurate because the selling price is rounded in simulation API. Sometimes when the unit multiplier is an integer value or maybe due to coincidence you will have the price matching, but, when the price is float, the price won't be accurate in most the cases and you will have the discrepancy of cents due to the rounded sellingPrice being divided by a float number in unitMultiplier
So, to fix it, the correct value of price should be price/100 + priceTags, because sellingPrice is always rounded in simulation API, and price and priceTags are always the full prices. With that, we will have more precision …
> fix: inaccurate price due to the rounded sellingPrice in simulation API

- CHANGELOG.md
- graphql/types/Logistics.graphql
- Currently when retrieving the store information, there weren't any store hours for the holidays, this was added
- Using the GraphhQL IDE create a query using any `store id`
- Using it in a working workspace [here](https://beto--productusqa.myvtex.com/store/mexico-pickup-point-ciudad-de-mexico-03580/Mexico1)
> Add holidayHours query to logistics

- CHANGELOG.md
- node/typings/Checkout.ts
- node/utils/simulation.ts
This PR reverted changes made at #608 that caused prices to be wrong displayed in product list pages:
[Workspace](https://danzan--masonlineprod.myvtex.com/donuts?_q=donuts&map=ft)
Related escalation: https://vtex.slack.com/archives/C017NPK8U86/p1658826643797209
> Reverts change on how to calculate price in `commertialOffer`

- CHANGELOG.md
- graphql/types/Logistics.graphql
This pr try to solve this problem
```cmd
error:build.status: fail - New GraphQL route types or parameters have been added since the previously published version of the app. This app should be published as a new minor.
New features:
HolidayHours was added.
PickupPoint.pickupHolidays was added.
```
So, we try to re-publish the graphql as a minor
> fix: remove white space on graphql schema

- CHANGELOG.md
- node/clients/profile/profileV2.ts
https://vtex.slack.com/archives/G016AGYHTV2/p1655995368610139
[Workspace](https://vtex.slack.com/archives/G016AGYHTV2/p1655995368610139https://fixaddress--gmheritageprod.myvtex.com/account)
Create a new profile (by accessing the user profile page) and create a new address. This should work just fine. It is not in stable.
Happy
> Fixing bug PII address street number null

- node/yarn.lock
Reverts vtex-apps/store-graphql#614
Reverting again because it was reverted due to another problem that had nothing to do with those changes.
> Revert "Revert "Bump y18n from 4.0.0 to 4.0.3 in /node""

- CHANGELOG.md
- node/package.json
- node/yarn.lock
We are updating dependencies to solve some security issues alerted by `dependabot`.
Those below are the ones that `dependabot` couldn't update automatically:
1. https://github.com/vtex-apps/store-graphql/security/dependabot/50 -> `json-schema`
2. https://github.com/vtex-apps/store-graphql/security/dependabot/82 -> `jsdom`
3. https://github.com/vtex-apps/store-graphql/security/dependabot/16 -> `node-notifier`
Nothing should've changed: [workspace](https://laricia--storecomponents.myvtex.com/)
> Update versions of json-schema, jsdom and node-notifier

- CHANGELOG.md
- node/package.json
- node/yarn.lock
We are updating dependencies to solve some security issues alerted by `dependabot`.
`dependabot` couldn't update automatically those:
1. https://github.com/vtex-apps/store-graphql/security/dependabot/51
2. https://github.com/vtex-apps/store-graphql/security/dependabot/58
Both are related to `follow-redirects`.
Nothing should've changed: [workspace](https://laricia--storecomponents.myvtex.com/)
> Update follow-redirects version

- CHANGELOG.md
- node/package.json
- node/yarn.lock
We are updating dependencies to solve some security issues alerted by `dependabot`, but`dependabot` couldn't automatically fix [this alert](https://github.com/vtex-apps/store-graphql/security/dependabot/78).
The [new version of `busboy`](https://github.com/mscdex/busboy) removes this `dicer` package, so we are updating this one to fix this issue.
Nothing should've changed: [workspace](https://laricia--storecomponents.myvtex.com/)
> Update busboy version to remove dicer

- CHANGELOG.md
- node/directives/authorizationMetrics.ts
This PR adds sampling to the `authorizationMetrics` directive logs.
We found that logs with the message `Private route being accessed by unauthorized user` are responsible for sending **3GB of data to Splunk by hour**.
So, this PR adds a random function to reduce the amount 100x, decreasing the amount logged to 30MB per hour.
Nothing should have changed, and the amount logged should decrease
> Adds sampling on authorizationMetrics logs

- CHANGELOG.md
- graphql/types/OrderForm.graphql
When adding an address with `isDisposable: true` the address is saved in MasterData anyways.v It was described here: https://github.com/vtex-apps/store-graphql/issues/541
```
curl --location --request PUT 'https://isdisposable--modeloramamx.vtexcommercestable.com.br/api/checkout/pub/orders' \
--header 'VtexIdclientAutCookie: ' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
"items": [
{
"id": "49",
"quantity": 1,
"seller": "modeloramamxnorte"
},
{
"id": "58",
"quantity": 1,
"seller": "1",
"price": 0
}
],
"clientProfileData": {
"email": "lucas.vysk@vtex.com",
"firstName": "Lucas",
"lastName": "v",
"document": "00000",
"documentType": "cedulamx",
"phone": "+529999",
},
"shippingData": {
"address": {
"addressType": "residential", …
```
> add `isDisposable` to address graphql

- CHANGELOG.md
- node/utils/simulation.ts
Tax was being returned cached instead of hot when using simulation call
Log into and check the shelves
[Workspace](https://testvtex2--coexitob2b.myvtex.com/?)
To ask for credentials, DM me please
Before:
After:
https://github.com/vtex/intelligent-search-api/pull/45
> feat: simulation now returning hot and not cached tax

- CHANGELOG.md
- node/utils/simulation.ts
Product search query wasn't returning the `PaymentSystemGroupName` prop because `itemsWithSimulation` didn't have this value
[Workspace](https://thalyta--carrefourbr.myvtex.com/admin/graphql-ide)
Before:
After:
> Add PaymentSystemGroupName to itemsWithSimulation response

- CHANGELOG.md
- graphql/schema.graphql
- node/directives/index.ts
- node/directives/monitorOrigin.ts
This PR adds a directive to monitor the origin of all requests to the `orders` endpoint.
Install a beta version and make a request to the orders endpoint using postman or curl
> Adds directive to monitor origin of orders endpoint

- CHANGELOG.md
- manifest.json
- node/clients/profile/profileV2.ts
- node/globals.ts
- node/resolvers/profile/services.ts
My account was unable to access / edit / save addresses created in the new profile system.
Adjustment of the mapping according to the fields saved natively by the checkout.
Beta version: vtex.store-graphql@2.161.2-beta.2
Test the native purchase/edit flow via my account:
https://bibiclean--casinofrqa.myvtex.com/
Workspace with changes: 
To test it you must be at an IP address at France (use VPN)
[Workspace](https://withouttheme--casinofrqa.myvtex.com)
The changes were made considering the schema:
https://github.com/vtex/storage/blob/main/schemas/address/address-fra.json
and the checkout flow:
https://github.com/vtex/vcs.checkout/blob/master/src/VTEX%20Checkout/Private%20Assemblies/Vtex.Commerce.Checkout.Services/ClientProfile/V2/ClientProfileServiceV2.cs#L387
> change fields for address at profile V2

- CHANGELOG.md
- node/resolvers/profile/services.ts
Mutation was breaking for addressId null:
It should save the Address:
Use the saveAddress mutation passing a body like:
```
{
"address": {
"city": "TESTE",
"addressName": "TESTE",
"country": "BRA",
"addressType": "residential",
"complement": "",
"number": "10",
"geoCoordinates": [
-49.34089660644531,
-25.471193313598633
],
"neighborhood": "TESTE",
"postalCode": "22222222",
"receiverName": "TESTE",
"state": "RJ",
"street": "TESTE",
"reference": ""
}
}
```
After change:
> Fix: Save Address Mutation

- CHANGELOG.md
- node/resolvers/checkout/index.ts
- node/utils/flags/flagRegionalization.ts
- node/utils/flags/regionFlag.ts
- node/utils/regionV1.ts
- node/utils/simulation.ts
Add the campaign context for the simulation.
With the context:
```
curl --location 'https://bibi--northlatamprojects.vtexcommercestable.com.br/api/io/_v/api/intelligent-search/product_search/trade-policy/1/%2F?simulationBehavior=default&count=10&page=1&hideUnavailableItems=false&query=1661366' \
--header 'Cookie: VtexWorkspace=master%3A-; janus_sid=a02b1cd8-8add-4351-aecc-2875de14f049; vtex_segment=eyJjYW1wYWlnbnMiOiI5YmRiYjYwZC02MDY5LTQ2MzYtOGY3ZS0wZmViODMzMmZjZGUiLCJjaGFubmVsIjoiMSIsInByaWNlVGFibGVzIjpudWxsLCJyZWdpb25JZCI6bnVsbCwidXRtX2NhbXBhaWduIjpudWxsLCJ1dG1fc291cmNlIjpudWxsLCJ1dG1pX2NhbXBhaWduIjpudWxsLCJjdXJyZW5jeUNvZGUiOiJDT1AiLCJjdXJyZW5jeVN5bWJvbCI6IiQiLCJjb3VudHJ5Q29kZSI6IkNPTCIsImN1bHR1cmVJbmZvIjoiZW4tVVMiLCJhZG1pbl9jdWx0dXJlSW5mbyI6ImVuLVVTIiwiY2hhbm5lbFByaXZhY3kiOiJwdWJsaWMifQ …
```
> Add: Campaigns object to simulation

- CHANGELOG.md
- graphql/types/Order.graphql
- graphql/types/Shipping.graphql
Products are allowed to add float values in unitMultiplier, such as kilogram and meter types, for example:
Select store-graphql at: [Workspace](https://iespinoza--cassol.myvtex.com/admin/graphql-ide)
Query:
```
query getShippingEstimates(
$items: [ShippingItem]
$postalCode: String
$country: String
) {
shipping(items: $items, postalCode: $postalCode, country: $country) {
items {
id
seller
sellerChain
price
listPrice
sellingPrice
measurementUnit
unitMultiplier
}
logisticsInfo {
itemIndex
slas {
id
friendlyName
price
shippingEstimate
shippingEstimateDate
deliveryChannel
}
}
}
}
```
```
{
"items": [
{
"id": "1638431",
"quantity": 1,
"seller": "1"
}
],
"country": "BRA",
"postalCode": "49032-000"
}
```
Zendesk: #869926
> fix: UnitMultiplier type from simulation call is always a float number

- CHANGELOG.md
- node/resolvers/profile/services.ts
Add a filter to not show "pickup" AddressType at the my account.
Before:
After:
This type of address should not be saved at the user profile  but different from Profile V1 the Profile V2 saves it so we are filtering by those in order to nor impact the User Experience.
> Add: filter logic for "pickup" addressType

- CHANGELOG.md
- node/clients/profile/profileV2.ts
Error when saving address in Ireland:
This API fails when the administrativeAreaLevel1 is null due to the schema validation:
Try add a new address at my account for ireland at the master and after at this workspace:
[Workspace](https://address--dunnesstoresqa.myvtex.com/account#/addresses)
> add fallback value

- CHANGELOG.md
- node/clients/profile/profileV2.ts
- node/resolvers/profile/services.ts
Cards saved at a profile using PII are not retrieved at my account. 
The first problem is that the API to retrieve the `purchase-info` does not accept the alternativeKey param and it was calling the API with the unmasked path twice like `unmasked/unmasked`. So when this API was being called it was returning 404 even when the profile had already purchase infos saved to it. 
Ex:
`http://portal.vtexcommercestable.com.br/api/storage/profile-system/profiles/beatriz.maselli@vtex.com/purchase-info/unmask?alternativeKey=email&useCase=MyAcocunts&onBehalfOf=user&an=dunnesstoresqa`
This will return 404. ❌ 
Calling using the userId:
`http://portal.vtexcommercestable.com.br/api/storage/profile-system/profiles/5f2e2bf9-13ba-4679-9ce4-5877fee681e6/purchase-info/unmask?useCase=MyAcocunts&onBehalfOf=user&a …
> Fix/ Retrieve saved cards for at Profile System for PII accounts

- CHANGELOG.md
- node/directives/withCurrentProfile.ts
Check user email with toLowerCase to prevent error when the identity user has difference from token
https://vtex-dev.atlassian.net/browse/OMS-6340
https://profile--dunnesstorespreprod.myvtex.com/account#/profile
User: DQA57@test.com
Password: Dunnes123 
[Workspace](https://profile--dunnesstorespreprod.myvtex.com/account#/profile)
> check user email with toLowerCase

- CHANGELOG.md
- node/dataSources/identity.ts
- node/directives/withCurrentProfile.ts
Now it's possible to navigate at VTEX without email, it's a new feature called email rectification. In this scenario, the validation must be done by the customerId. From now on, every user will have their own customerId and it's supposed to not use email as a primary key anymore
You must follow several steps in order to create your user with the permissions, so, when reviewing this, please, contact to me so I can give you the access
- Log with your authorized email in account b2bsuite
[Before](https://b2bsuite.myvtex.com/account#/profile)
[After](https://iespinoza--b2bsuite.myvtex.com/account#/profile)
> fix: error when no email found in jwt due to email rectification feature

- CHANGELOG.md
- node/clients/oms.ts
- node/index.ts
- node/routes/index.ts
- node/service.json
This pull request introduces a new feature to fetch email rectification configuration from the OMS service. The most important changes include adding a new method to the `OMS` client, updating the service configuration to include a new route, and implementing the route handler.
We need this to make this route accessible only to authenticated shoppers using the application token to retrieve the configuration.
[Workspace](https://myordergql--storecomponents.myvtex.com/_v/private/rectification-config)
* [`node/clients/oms.ts`](diffhunk://#diff-e7dd1712e4256837e1a9bb4af6d18babaed4555cac29a8ccf95e8bdbc785b3aaR55-R60): Added a new method `getRmailRetificationConfig` to fetch email rectification configuration from the OMS service.
* [`node/index.ts`](diffhunk://#diff-8843f11df3c9cd9d4e863c06541e9 …
> Add route to return the rectification config value

- CHANGELOG.md
- manifest.json
[#inc-3353-esc](https://vtex.enterprise.slack.com/archives/C0954P4C0CE)
This pull request updates the `manifest.json` file to include a new entry for "AdminPortal" in the list of components.
* [`manifest.json`](diffhunk://#diff-ffa5b716b5a57837f7929dfcca4b4dfdeb97210a7fd5a12d2f1978846d6f1743R131-R133): Added a new component named "AdminPortal" to the configuration.
[Workspace](https://storeconfig--recorrenciacharlie.myvtex.com/admin/graphql-ide)
```
{
storeConfigs{
siteTitle
tagManagerId
kiosk
tagManagerId
googleMapsApiKey
ioExtensions
}
}
```
> feat: Add AdminPortal to the list of policies in manifest.json

- CHANGELOG.md
- manifest.json
- node/clients/catalog.ts
- node/resolvers/profile/services.ts
This PR addresses an issue with email rectification by users in the store-graphql API. The current implementation was allowing email rectification from users when it should be prevented, allowing rectifications just from Admin.
Already tested by Gabriel Fuentes Rojas from Sec Red Team, from Sec perspective. 
There are some steps to validate, so please contact me when reviewing and I can provide the workspace and the details.
No visual changes - this is a backend API fix for email rectification validation logic.
- Prevent email rectification from user
> fix: Prevent email rectification from user
